### ISSUE TITLE
Add CI test for sdist and coda package

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#105]
I've been bitten a few times last year with making releases and only after noticing little mistakes.

So starting here with regions and then Gammapy, I would like to take the time this week and add CI builds that generate sdist and conda packages, and install and test those, before making the upcoming releases.

@bsipocz @astrofrog - How would you recommend to add this? As a lengthly multi-line string in the `.travis.yml`, or a bash script somewhere that I execute from `.travis.yml` or a Makefile?

In any case, I guess I should use the existing setup and use a `MAIN_CMD` and empty `SETUP_CMD` like here?
```
env: MAIN_CMD='pycodestyle regions --count' SETUP_CMD=''
```
https://github.com/astropy/regions/blob/master/.travis.yml#L92

**Comment by bsipocz** [comment]
I have mixed feelings about this, while the idea of testing the the packaging before doing the release is great, I feel it's wasting CI resources for doing it for each and every merge commit. That being said, I don't have a good alternative idea.

One way to control it, is to run that job in travis from cron only. E.g. weekly builds. Or only trigger that cron once the branching is done (on that given branch it can be part of a daily cron?). 

Another, more manual approach, is to have a generic script, put it into ``astropy-tools``, or a similar place, and make it part of the suggested release procedure to run those scripts.

**Comment by cdeil** [comment]
@bsipocz - Ah, OK. I agree that this doesn't need to run in CI.

So I just now tried step 12 from
http://docs.astropy.org/en/latest/development/affiliated-packages.html#releasing-an-affiliated-package
and basically those instructions work and there are no issues in the regions sdist:
```
conda create -n regions_rel_test astropy
source activate regions_rel_test
pip install pytest-arraydiff
python setup.py sdist
cd dist
pip install regions-0.2.dev375.tar.gz
python -c 'import regions; regions.test()'
source deactivate
cd ..
```

The main other thing I'd like to do before releasing sdist to PyPI it build a conda package, install it and run tests locally. This is the same thing already discussed at https://github.com/astropy/conda-channel-astropy/pull/99#issuecomment-262304462 .

> Another, more manual approach, is to have a generic script, put it into astropy-tools, or a similar place, and make it part of the suggested release procedure to run those scripts.

Having a script that makes this a bit quicker (e.g. not have to type package name, dependencies, version number) would be convenient.

But already, if anyone knows how to build the conda package from the local sdist and add it as an optional step here: http://docs.astropy.org/en/latest/development/affiliated-packages.html#releasing-an-affiliated-package
that would be what I would want to do everytime before I release a package.

I'll be offline now, but try to figure out the conda commands to do it tomorrow.

**Comment by bsipocz** [comment]
Your guess is as good as mine regarding the conda test packaging (I would change the url to be local one pointing to the sdist in a recipe template generated with ``extrude_recipes`` and the ``conda build-all``, but I would be very surprised if that works out of the box).

So it's best pinging @mwcraig as he may have better ideas about this.

**Comment by cdeil** [comment]
So I tried to follow the release procedure just now:
```
git clean -fxd
python setup.py build sdist --format=gztar
cd dist
tar zxvf regions-0.2.tar.gz
cd regions-0.2
```
and this is failing:
```
$ python setup.py test
running test
running build
running build_py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/regions-test-2wlffxv0/lib.macosx-10.12-x86_64-3.5/regions/__init__.py", line 23, in <module>
    from .io import *
  File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/regions-test-2wlffxv0/lib.macosx-10.12-x86_64-3.5/regions/io/__init__.py", line 4, in <module>
    from .read_ds9 import *
  File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/regions-test-2wlffxv0/lib.macosx-10.12-x86_64-3.5/regions/io/read_ds9.py", line 13, in <module>
    from ..shapes import circle, rectangle, polygon, ellipse, point
  File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/regions-test-2wlffxv0/lib.macosx-10.12-x86_64-3.5/regions/shapes/__init__.py", line 4, in <module>
    from .circle import *
  File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/regions-test-2wlffxv0/lib.macosx-10.12-x86_64-3.5/regions/shapes/circle.py", line 12, in <module>
    from .polygon import PolygonSkyRegion
  File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/regions-test-2wlffxv0/lib.macosx-10.12-x86_64-3.5/regions/shapes/polygon.py", line 9, in <module>
    from .._geometry import polygonal_overlap_grid
  File "/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/regions-test-2wlffxv0/lib.macosx-10.12-x86_64-3.5/regions/_geometry/__init__.py", line 7, in <module>
    from .circular_overlap import *
ImportError: No module named 'regions._geometry.circular_overlap'
```
Looking into the issue / try to find a solution now ...

**Comment by bsipocz** [comment]
@cdeil - weirly it seems that the ``regions`` directory is missing from MANIFEST.in? L8 should be probably ``recursive-include *.pyx *.c *.pxd`` --> ``recursive-include regions *.pyx *.c *.pxd``

**Comment by cdeil** [comment]
OK, I've fixed `MANIFEST.in` as you suggest in e66515a

@bsipocz - Thanks for pointing out the right fix!

Actually, I've seen that issue before, at least for Gammapy, where I fixed it two years ago:
https://github.com/gammapy/gammapy/commit/4a6deef8e3a02bd6cd98fc88316b4b686faf5ef8

**Comment by bsipocz** [comment]
Yes, we've fixed it not long ago in the package template, so there may be still a few affiliates out there that have this bug.

**Comment by cdeil** [comment]
I'm closing this issue. The plan is to merge this package into `astropy.regions` eventually, so no need to spend too much time on setting up better CI for it.

Just for reference, in Gammapy I did end up adding a build for `python setup.py bdist_conda` that builds a conda package and runs a bunch of checks (e.g. that all modules can be imported and all cli tools can be run with `--help`). We also have a Makefile and release checklist and there's make targets that do extra checks that don't need to run in CI, but just before making a release.
