### ISSUE TITLE
Remove PixCoord.isscalar?

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#108]
@astrofrog @larrybradley @keflavich - Should we remove `PixCoord.isscalar`?

It's currently implemented as `np.isscalar(self.x)`:
https://github.com/astropy/regions/pull/106/files#diff-23129064d4c4f77992faa0ddb1fcabe8R91

I just noticed that this doesn't really do what I expected:
https://github.com/astropy/regions/pull/106/files#diff-6d4df9d4594341f07b19601a398cde45R104

Someone else (I think) also used it incorrectly here:
https://github.com/astropy/regions/pull/106/files#diff-23129064d4c4f77992faa0ddb1fcabe8R147

Basically what we sometimes want is to check if `pixcoord` represents a single point or multiple points, but because `np.isscalar(np.array(42)) == False` this doesn't represent that question, and e.g. when we run `pixcoord = skycoord.to_pix(wcs)` we get pixcoord objects that have 0-dim numpy arrays (like what you get from `np.array(42)`.

So I could try to remove `pixcoord.isscalar` and all callers (and if needed tests) and post a commit here for review. Or do we want / need it and there's some way to make the current situation better?

(my time is very limited this week, if someone else can make a PR for this, it would be much appreciated)

**Comment by bsipocz** [comment]
I've run into similar issues when tried to fix astroplan, the solution there was to use ``astropy.utils.isiterable``  to check on ``SkyCoord`` objects, rather than hacking with ``isscalar``. Probably is should work here, too and then there is no need for ``isscalar``.

**Comment by cdeil** [comment]
I see that `SkyCoord` inherits `isscalar` from [astropy.utils.misc.ShapedLikeNDArray](http://docs.astropy.org/en/latest/api/astropy.utils.misc.ShapedLikeNDArray.html)

```
@property
    def isscalar(self):
        return self.shape == ()
```

So I guess there's a few options here:
1. Remove `PixCoord.isscalar`
2. Change the `PixCoord.isscalar` implementation to match what `SkyCoord` does
3. A more substantial change to `PixCoord`, e.g. trying to inherit from `ShapedLikeNDArray`.

I'm still looking for opinions here (or even volunteers to make a PR), will leave as-is for now.

**Comment by cdeil** [comment]
I'm doing a minimal change now (see #110), but I'll keep this issue open for discussion. Changing the milestone to 0.3.

Probably making `PixCoord` a sub-class of `ShapedLikeNDArray` would be a good long-term solution? Is `SkyCoord` the best example to look at, or are there simpler examples in the Astropy code or test or in other packages that one can study to see how it works?

**Comment by larrybradley** [comment]
I think using the `Skycoord.isscalar` representation is fine.  I'm not sure we really need all of the other functionality that comes with `ShapeLikeNDArray`.

**Comment by cdeil** [comment]
So probably there's nothing to do here. Closing the issue now.

If someone thinks this point can be improved, feel free to make a pull request or re-open this issue for discussion any time.
