### ISSUE TITLE
Implement composite regions in ds9 parser

### ISSUE THREAD

**Issue by keflavich** [astropy/regions#11]
This probably requires implementation of composite regions... anywhere.

Composite regions should have at least:
- [ ] container for other regions
- [ ] some method to convert to matplotlib patch collections

**Comment by joleroi** [comment]
There is an API for compound/composite regions

https://github.com/astropy/regions/blob/cd95c9ea3654a02154d90c1c1e7d9cf89a577d10/regions/core/compound.py#L6

Does anyone know why it's only for 2 regions? Don't we want to combine any number of regions?

cc @astrofrog

**Comment by astrofrog** [comment]
@joleroi - because any combination of more regions can be represented by a nested pair of binary combinations. For instance, if you do ``r1 + r2 - r3`` it's easiest to represent this as ``((r1 + r2) - r3)``. Does this make sense?

**Comment by joleroi** [comment]
How would the API look in this case? Say you have 5 circles (c1 to c5) and want to combine them. Intuitively I would expect this

```
combined_region = c1 + c2 + c3 + c4 + c5
```
So I would overload the __add__ function an return a CompoundSkyRegion. 
Now thinking about it while typing that's exactly what the suggested API does, right?

**Comment by astrofrog** [comment]
@joleroi - yes, this is what I had in mind here:

https://github.com/astropy/regions/blob/master/regions/core/core.py#L35

Now we should think carefully about which operators make sense in the case of regions. Do we want:

```
combined_region = c1 & c2 & c3 & c4 & c5
```

or

```
combined_region = c1 + c2 + c3 + c4 + c5
```

for instance? At the moment I had assumed we would use logical operators, but not sure if that or arithmetic operators make more sense?

**Comment by joleroi** [comment]
These are to different things, aren't they,  I would expected
```
c1 + c2
```
to return the union of c1 and c2 and
```
c1 & c2
```
the intersection (probably not super easy to implement)

**Comment by astrofrog** [comment]
@joleroi ah yes sorry, a better example in that case would be ``c1 + c2`` vs ``c1 | c2``

**Comment by joleroi** [comment]
Ah ok, in this case ``c1 | c2`` is probably more straightforward isn't it? I can make a PR and try to implement this, ok?

**Comment by astrofrog** [comment]
@joleroi - sounds good!
