### ISSUE TITLE
Is source in FoV

### ISSUE THREAD

**Issue by dagnic** [astropy/regions#118]
Hello, 

I'm working on the SVOM mission and I'm really interested in the astropy/region package. 

We have a squared fov (89*89deg) centered on a known (ra_0,dec_0) position and I would like to determine if a source located at (ra_s, de_s) would be present in the fov. We also know the roll angle.

I've seen that method contains.RectangleSkyRegion is not yet implemented. Do you have an idea to achieve that ? I think that it as to deal with spherical trigonometry.

Thanks for your help, 
Cheers, 

Nicolas

**Comment by cdeil** [comment]
@dagnic - We discussed this question of how to implement `contains` for rectangle sky region and came to the conclusion that it's not well-defined and that we'd never provide it:
see https://github.com/astropy/regions/issues/107

But of course, if you can come up with a useful implementation for it we could put that. Is it clear to you if it's possible? If yes, do you think you could come up with an exact description or even a function how it could be implemented?

**Comment by cdeil** [comment]
Also -- 89 x 89 deg -- that's impressive! Congratulations on your large FOV!
:-)

**Comment by dagnic** [comment]
Thanks, I will think about it. I'll keep you in touch.

**Comment by cdeil** [comment]
@dagnic - This is what we have now:

https://astropy-regions.readthedocs.io/en/latest/_modules/regions/shapes/rectangle.html#RectangleSkyRegion.to_pixel

It's a RectangleSkyRegion that, given any WCS projection, can be transformed back and forth to a RectanglePixelRegion. The sky region has no contains, but the pixel region does.

I'm not sure if that helps with your task, but I'm also not sure what else we could / should implement here.

@dagnic - Thoughts?
