### ISSUE TITLE
Feature Request: CASA region reader/writer

### ISSUE THREAD

**Issue by keflavich** [astropy/regions#119]
See http://stackoverflow.com/questions/43761841/astropy-table-with-source-positions-save-in-casa-region-format

cc @vilhelmp

**Comment by keflavich** [comment]
definition of the region format: https://casaguides.nrao.edu/index.php?title=CASA_Region_Format

**Comment by keflavich** [comment]
the casa libraries are in casacore and are complicated:
https://github.com/casacore/casacore/tree/master/images/Regions
It would be unwise to try to wrap those, I suspect.

**Comment by keflavich** [comment]
There's a new home for the region specification:
https://casa.nrao.edu/casadocs/casa-5.2/image-analysis/region-file-format

**Comment by sushobhana** [comment]
#173 and #186 implements the reader and writer for CRTF. The round trips seems to work well under the limited example set available to us. In future, there is a need to improve the test suite once we gather sufficient sample files.
