### ISSUE TITLE
regions version 0.3

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#125]
I think we should make a regions 0.3 release next week.
We can use this issue to discuss.

There is a 0.3 and 0.4 milestone, so anyone feel free to add or move issues / PRs to those:
https://github.com/astropy/regions/milestones

There already are some new features and fixes since the 0.2 release, and more are coming this week. A release is not much work and in my experience helps to focus the work and make sure discussions conclude, issues get closed and PRs finished and merged.

I would prefer if someone else does it! @joleroi @keflavich ?
If no, I could do it Thursday, May 18. Let me know.
In any case, I can spend a few hours to work on `regions` early next week.

If some has plans to work a lot on `regions` in the coming weeks, we can also postpone for a few weeks. (But why do 0.3 next week and 0.4 in a month or two?)

**Comment by cdeil** [comment]
I've gone through the open issues and PRs.
These are the issues / PRs I would consider blockers before we should put out regions 0.3:
https://github.com/astropy/regions/milestone/5

Everyone: feel free to change milestones if you think something else should go in 0.3 or can be put off to 0.4.

**Comment by bsipocz** [comment]
@cdeil - Today I've run into a rather misleading segfault when tried to build and test gammapy. It turned out to be related to regions cannot be installed as I had 1.6+ sphinx later causing the fault in the gammapy cython code. 

So I wonder about the ETA for the new release here? If needed I can help out a bit.

**Comment by cdeil** [comment]
There's still 8 open issues under https://github.com/astropy/regions/milestone/5 . The problem is that no-one has time to work on regions, it seems. I'm not sure what to do. I could spend half a day max next weekend to try and resolve some of those issues and put out a release in whatever we have until then if the current v0.2 release is broken in some cases. Would that be helpful or is it even urgent to do?

**Comment by bsipocz** [comment]
Well, it's not super urgent, but I think it's would be rather useful to have a bugfix out sooner rather than waiting for those issues to be solved (with a quick glance none seems to be a bug).

**Comment by cdeil** [comment]
@keflavich @astrofrog @sushobhana - Can we release v0.3 in the next days?

Please have a look at https://github.com/astropy/regions/milestone/5 and add something to the milestone if it's essential.

IMO the only thing we really should wait for is for #208 to land.

If one of you has time to make the release, great!
Otherwise I can do it.

**Comment by sushobhana** [comment]
I will try to finish #208 , #203 by today

**Comment by cdeil** [comment]
@keflavich @astrofrog @sushobhana - OK to release regions v0.3 now?

Given that we don't have a changelog, I'm not sure how to summarise the progress since v0.2.

Ideally we'd add a CHANGES.rst like in other packages.

This is the announcemnt from the last release:
https://groups.google.com/forum/#!searchin/astropy-dev/regions%7Csort:date/astropy-dev/uvFZL0zmBcA/qcqBcR5vDgAJ

**Comment by sushobhana** [comment]
@cdeil most of the major developments are done in this summer. I can summarize it.
From now on we can keep the track of changes in the `CHANGES.rst`. What say??

**Comment by cdeil** [comment]
It would be best if you already add a changelog now and summarise the versions up to what we have now there. You don't have to list PRs, just one heading with the version number and date of existing releases and the upcoming v0.3 would be enough.

Example: https://hips.readthedocs.io/en/latest/changelog.html

You can see the dates for v0.1 and v0.2 here: https://pypi.org/project/regions/#history

I actually mean "best" for me, it's a bit of work for you. :-)

**Comment by larrybradley** [comment]
@sushobhana Thanks for all your great work this summer!  🎉

**Comment by cdeil** [comment]
@sushobhana - Thank you for all your work on regions and for agreeing to do the regions v0.3 release now! I've added you as maintainer on https://pypi.org/project/regions/ , and you should also have permissions to push tags and make the release on Github now, so you can go ahead whenever you have time.

**Comment by sushobhana** [comment]
Added the tag and uploaded to PyPi !!

**Comment by cdeil** [comment]
@sushobhana - Thanks!

Works for me with pip install using a Python 3.6 from conda on macOS.

Does anyone know if there is a bot that will open a PR to update to v0.3 at https://github.com/conda-forge/regions-feedstock ? Or should we make a PR manually?

**Comment by cdeil** [comment]
Looks like RTD picked up the stable tag automatically.
This is already there: https://astropy-regions.readthedocs.io/en/v0.3/

**Comment by cdeil** [comment]
I see: there's a conda-forge bot that opened https://github.com/conda-forge/regions-feedstock/pull/5

**Comment by cdeil** [comment]
The conda-forge packages for regions v0.3 are in place.

@sushobhana - Please to ahead and announce this release on the astropy-dev mailing list, and then close this issue and the v0.3 milestone.

**Comment by sushobhana** [comment]
@cdeil away from my laptop now. Will do it on Wednesday. Sorry for the delay!

**Comment by sushobhana** [comment]
Thanks @cdeil for all the help. Also, thanks @larrybradley - used your release mail for photutils as the template (saved a little time!).
The announcement - https://groups.google.com/forum/#!topic/astropy-dev/dv7b8L-FnoE

**Comment by bsipocz** [comment]
Thank you @sushobhana and all involved to make this release happen!
