### ISSUE TITLE
How to convert between pixel & sky?

### ISSUE THREAD

**Issue by keflavich** [astropy/regions#13]
What approach will be the default for converting between pixel and sky?  Probably all of these should be implemented, but one should be the default:
- convert all regions to polygons, convert sky coordinates to pixel and vice versa
- keep circles, rectangles, etc. "fixed", convert by assuming the projection is perfectly flat

Contained in option 1 is a question about how accurately we need to discretize continuous shapes when converting to polygons.

Also, which regions will get "abstract" representations allowing them to be rotated and manipulated with simple parameters?  e.g., ellipse, rectangle have major/minor axes and angles that are their minimal representations, but these are not preserved through projection.

**Comment by astrofrog** [comment]
Just FYI, the difference between the two bullet points is the difference between the ``affine`` and ``full`` flags in ``to_pixel`` and ``to_sky`` in the currently API. And for the ``full`` mode, we've planned to have a ``tolerance`` keyword that addresses your point about how accurate the polygons have to be.

**Comment by joleroi** [comment]
FYI: I added some implementation of ``to_pixel`` for the ``CircleSkyRegion`` in https://github.com/astropy/regions/pull/29. This needs to be checked
