### ISSUE TITLE
How to cutout mask from an image

### ISSUE THREAD

**Issue by joleroi** [astropy/regions#138]
Consider the following example

```
import matplotlib.pyplot as plt
import numpy as np
from regions import CirclePixelRegion, PixCoord
center=PixCoord(10,10)
circle=CirclePixelRegion(center, 5)
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
np.random.seed(12345)
data=np.random.random((20,20))
mask=circle.to_mask()
data[mask.bbox.slices] *= 1 - mask.data
ax.imshow(data, interpolation='nearest', cmap='viridis')
ax.add_patch(circle.as_patch(facecolor='none', edgecolor='red'))
```
![figure_1](https://cloud.githubusercontent.com/assets/11678435/26497648/7ddbe456-422c-11e7-9b17-2edbf32e250d.png)

This is a common use case I have, and also what I would have expected that [Mask.cutout(image)](http://astropy-regions.readthedocs.io/en/latest/api/regions.Mask.html#regions.Mask.cutout) would do. It doesn't, which I guess is fine since many/most other people will need the functionality that is currently implemented.

Do agree that my use case also be added to the API somehow? I suggest

```
mask.cutout_from(image)
```
Or is this too confusing?

**Comment by keflavich** [comment]
So... you want to set the values within a mask to zero?  Could you explain what the use case is for that?

My general use case looks like this:
```
        mask = pixreg.to_mask()
        cutout = mask.cutout(data) * mask.data
```
which takes the minimal cutout region and then sets the pixels *outside* the mask to zero.  At least, that's what I want... I hope it's still doing that.

**Comment by joleroi** [comment]
> Could you explain what the use case is for that?
I wanted to sum counts in a counts image excluding bins that contain source emission (background estimation)

> I hope it's still doing that.
I didn't change anything, this is a question/proposal to add another method. If this is controversial, I will just go on and use the 2 lines I put in the example. It's just not very intuitive for people not familiar with the regions package (you have to know about BoundingBox.slices).

**Comment by astrofrog** [comment]
I feel like this is too specific a use case and this would be a good chance to simply demonstrate in the docs how to do that with the current API.

**Comment by keflavich** [comment]
@joleroi don't you want to specify the background-estimation region more specifically than "the bounding box containing the region, excluding the region"?  When I do background estimation, I usually use an annular region.  It seems that you could accomplish the same goal by using a composite region of `rectangle xor circle`.   Am I missing the point?

**Comment by joleroi** [comment]
> don't you want to specify the background-estimation region more specifically than "the bounding box containing the region, excluding the region"?

What I am asking for is "the entire image excluding the region"

> I feel like this is too specific a use case and this would be a good chance to simply demonstrate in the docs how to do that with the current API.

Alright, maybe this is indeed better suited for gammapy, where it's a common use case.

**Comment by cdeil** [comment]
You could still make a regions docs example for that.

Masking out sources before background estimation is a common thing in astronomy, not just gamma-ray astronomy, see e.g.: https://photutils.readthedocs.io/en/stable/photutils/background.html

So basically what you have is a bunch of regions that were created to correspond to sources and emission, and to mask those out in an image?

I think it would be good to have a regions docs example how to do that, i.e. work with lists of regions and creating masks from them.

Side note: I see that in Gammapy we have this function which can make a mask for a single region: https://gammapy.readthedocs.io/en/latest/api/gammapy.image.SkyImage.html#gammapy.image.SkyImage.region_mask

**Comment by joleroi** [comment]
> So basically what you have is a bunch of regions that were created to correspond to sources and emission, and to mask those out in an image?

Exactly, for me this seems like an obvious thing we'd want to support, but if everyone prefers a docs example, that shall be it.

> Side note: I see that in Gammapy we have this function which can make a mask for a single region: 

I know, it'll probably need to be adapted with the next regions release though

**Comment by keflavich** [comment]
I'd like to see this in the docs first.  A convenience function to make the 'bbox' usage more accessible might make sense.
