### ISSUE TITLE
AttributeError: 'CompoundSkyRegion' object has no attribute '_repr_params'

### ISSUE THREAD

**Issue by mackaiver** [astropy/regions#156]
Title basically says it. When printing or displaying a CompundRegion in IPython I get

    AttributeError: 'CompoundSkyRegion' object has no attribute '_repr_params'

I'm on the latest release available on pypi.

**Comment by cdeil** [comment]
@mackaiver - Can you please share the example where you get the `AttributeError`?

I  just now tried the example from http://astropy-regions.readthedocs.io/en/latest/compound.html with the latest `master` and get this:
```
In [1]: %paste
from astropy.coordinates import Angle, SkyCoord
from regions import CircleSkyRegion
circle1 = CircleSkyRegion(
   center=SkyCoord(1,2, unit='deg', frame='galactic'),
   radius=Angle('5 deg')
   )
circle2 = CircleSkyRegion(
   center=SkyCoord(-4,3, unit='deg', frame='galactic'),
   radius=Angle('3 deg'),
   )
type(circle1 & circle2)

print(circle1 ^ circle2)
## -- End pasted text --
Region: CompoundSkyRegion
component 1: Region: CircleSkyRegion
center: <SkyCoord (Galactic): (l, b) in deg
    (1., 2.)>
radius: 5.0 deg
component 2: Region: CircleSkyRegion
center: <SkyCoord (Galactic): (l, b) in deg
    (356., 3.)>
radius: 3.0 deg
operator: <built-in function xor>
```

**Comment by mackaiver** [comment]
It works in master. It does not work for the release. Which is 0.2 I believe

**Comment by cdeil** [comment]
Closing issue. Please use master for now. We'll make a regions v0.3 soon.
