### ISSUE TITLE
Is photometric regions within the scope of astropy.regions?

### ISSUE THREAD

**Issue by astroferreira** [astropy/regions#16]
Hello

I wasn't present at any of the region discussion/sprint/unconference of PyAstro16 so I don't really know the scope of the project and its main goals, but defining photometric regions, e.g petrosian region in a single galaxy image, is within such objectives? I could really use something like that in some nonparametric morphology measurements I'm pushing to `photutils`.

Thank you

**Comment by keflavich** [comment]
I think it is in scope, but I'm not sure what such regions include.  Could you link to some literature describing these regions?

**Comment by astroferreira** [comment]
You can check that in the original paper [Petrosian, 1976](http://adsabs.harvard.edu/abs/1976ApJ...209L...1P) or maybe in one its applications [Lotz et al, 2004](http://adsabs.harvard.edu/abs/1976ApJ...209L...1P). It is a good way of defining the extends of a galaxy in an image, the Petrosian Radius does not depends explicitly in the cosmological model, making it a very useful tool while comparing galaxies at different redshifts. Another form of photometric region would be the region within the half-light radius, but that can be easily found by fitting a Sérsic profile.

**Comment by cdeil** [comment]
IMO `astropy.regions` is something very general ... represent regions, serialisation, masks.

Computing regions for galaxies is something application-specific that should go in [photutils](http://photutils.readthedocs.org/en/latest/) (which will import `astropy.regions` once the work here is done) instead of the Astropy core.

@larrybradley and @bsipocz as photutils maintainers - what do you think?

**Comment by larrybradley** [comment]
I completely agree with @cdeil.  Petrosian apertures are simply ellipses.  While the general elliptical region machinery will be handled in `astropy.regions`, the particular Petrosian ellipse parameters for a galaxy should be defined in `photutils`.  Same for half-light radius etc.  One also needs to handle overlapping sources/apertures, and that should also be in `photutils`.

**Comment by bsipocz** [comment]
@larrybradley @cdeil @keflavich - I had the impression that we had the conclusion that any photometry specific part of the apertures remain in photutils, while the generic region geometry/mask/etc will be moved over to regions.

**Comment by cdeil** [comment]
@astroferreira - Could you please close the issue in this `astropy.regions` tracker and open an equivalent one at https://github.com/astropy/photutils ?

I don't know how hard it is to compute these photometric regions. Would you maybe even be interested to take a stab at implementing one of them and make a pull request to photutils?

**Comment by astroferreira** [comment]
@cdeil I was planning in developing that myself, but I want to avoid any possible redundancy with `astropy.regions`,  I might just wait to use the `regions` machinery within `photutils` to do that instead of refactoring it once `regions` is ready. Thank you all for the discussion, should I just close this issue then?

**Comment by cdeil** [comment]
> I might just wait to use the regions machinery within photutils to do that instead of refactoring it once regions is ready

There will be nothing in `astropy.regions` that helps you compute the ellipse parameters.

FYI: It could easily be many months until the regions code that is being developed in this repo is finished and stable, included in the astropy core as `astropy.regions` and then shipped in a stable Astropy release. Only then will we update `photutils` to replace all the aperture code with `astropy.regions`.

So if you want to implement this, you should have your function return a table of ellipse parameters, or an [EllipticalAperture](http://photutils.readthedocs.org/en/latest/api/photutils.aperture_core.EllipticalAperture.html) object.
