### ISSUE TITLE
Add preferred citation

### ISSUE THREAD

**Issue by bsipocz** [astropy/regions#160]
Please add the preferred citation somewhere to the documentation (and preferable also to a CITATION file)

**Comment by cdeil** [comment]
@bsipocz - Is there a template or good example for CITATION for packages that don't have a paper.
Basically it's a sentence like this, no?

> This research made use of the Astropy regions package (https://github.com/astropy/regions).

Does it really make sense to offer a bibtex entry for that case?

**Comment by bsipocz** [comment]
Well, ideally I would prefer to have something with a DOI, probably zenodo requires the least effort to set up. 
(This issue was triggered that I try to dig up a reference for all affiliated packages to be cited in the astropy table).

**Comment by bsipocz** [comment]
Well, this came up again for referencing regions in the astroquery paper, so whenever someone gets to the point it would be great to get regions on zenodo and start getting citations.

**Comment by larrybradley** [comment]
Fixed in https://github.com/astropy/regions/pull/414
