### ISSUE TITLE
Managing definitions describing individual regions as in CRTF region files.

### ISSUE THREAD

**Issue by sushobhana** [astropy/regions#162]
Currently, the region classes has `meta` as well as `visual` attributes for describing them.
but there are no proper documentations for them . The possible keys and their values for the `meta` dictionary that are being already supported by DS9 region format is unclear.
The CRTF format has a long list of global parameters for each region/annotations.
The problem that appears when it is handled in the `meta` dictionary are:
1. The key can have different names and there is no way to check what user assigns.Ex: both `meta['veltype']='RADIO'` and `meta['velocitytype']='RADIO'` are possible which may lead to confusion.
2. There are specific possible values for  the key  that is valid but there is no way to check that.
3. The same key supported by both DS9 and CRTF formats may have different formats to store the same value.

The question is whether they should be handled as keys in the `meta` attribute or should be wrapped around a separate object or may be just create a new function to validate?
This applies for the `visual` attribute also.

**Comment by sushobhana** [comment]
I was going through the python language reference documentation and got to know about `__getattr__()` and how is it different from `__getattribute__()` and also about  `__setattribute__()` which would help us to store the meta data in meta dictionary (as it is now, internally) but we also can also access the keys of the dictionaries as attributes(through `__getattr__`), and also can check the validity of the value as well as assign them as attributes(through `__setattribute__`). 
I think this could solve the problem.!

**Comment by keflavich** [comment]
This Issue convolves several problems, which may all need to be addressed:
1. The metadata language for ds9, crtf, and possibly other region formats differ.  We need a translation layer to allow conversion between these.
2. There is presently little to no documentation of the metadata handling in `regions`.
3. Implementation details.

Let's handle #1 and #2 first.
