### ISSUE TITLE
New rectangular box type having two opposite corner points.

### ISSUE THREAD

**Issue by sushobhana** [astropy/regions#176]
casa region has a box type , `box[ [x1, y1], [x2, y2] ]` , the two coordinates are two opposite corners.
so, do we want to create a new region class for that? , or convert into current rectangle format to handle that.

**Comment by keflavich** [comment]
Convert to rectangle.  They are equivalent.

**Comment by cdeil** [comment]
Done by @sushobhana in #202 (still not merged)
