### ISSUE TITLE
conversion between pixel and sky region is inconsistent.

### ISSUE THREAD

**Issue by sushobhana** [astropy/regions#184]
```
from regions import *
from spectral_cube import SpectralCube

In [105]: reg_str
Out[105]: 'image\ncircle(2.5282832,3.4612342,1.3254484)'

In [106]: reg_str1
Out[106]: 'fk5\ncircle(1:36:14.969,+29:56:07.68,2.6509")'

In [107]: reg1 = DS9Parser(reg_str).shapes.to_regions()[0]

In [108]: reg1
Out[108]: <CirclePixelRegion(PixCoord(x=2.5282832, y=3.4612342), radius=1.3254484)>

In [109]: cube = SpectralCube.read('255.fits')

In [110]: reg11 = reg1.to_sky(cube.wcs.celestial)

In [111]: reg11
Out[111]: 
<CircleSkyRegion(<SkyCoord (FK5: equinox=2000.0): (ra, dec) in deg
    (24.06173553, 29.93602756)>, radius=0.0007364066385007544 deg)>

In [112]: reg2 = DS9Parser(reg_str1).shapes.to_regions()[0]

In [113]: reg2
Out[113]: 
<CircleSkyRegion(<FK5 Coordinate (equinox=J2000.000): (ra, dec) in deg
    (24.06237083, 29.93546667)>, radius=2.6509 arcsec)>

In [114]: reg2.radius.to('deg')
Out[114]: <Quantity 0.00073636 deg>

In [115]: reg21 = reg2.to_pixel(cube.wcs.celestial)

In [116]: reg21
Out[116]: <CirclePixelRegion(PixCoord(x=1.529699179565796, y=2.4594405907052987), radius=1.3253663090015846)>
```
Here, reg11 and reg2 are approximately equal,
but reg21 and reg1 are not same.
Isn't this weird?
Is it something because the frames of the center in reg11 and reg2 are not same?

**Comment by larrybradley** [comment]
It looks like you defined the sky coordinate in `reg_str1` from `reg_str` using 1-based pixels (`origin=1`) instead of 0-based pixels.  The `to_sky()` and `to_pixel()` methods use 0-based coordinates (`origin=0`).  That would explain why `reg21` is shifted by 1 pixel in x and y and why `reg11` is not exactly `reg2`.

**Comment by sushobhana** [comment]
I haven't defined anything, it was all implicit. And how can I make it 0 based pixels and any suggestion on how to come up with a fix?

**Comment by larrybradley** [comment]
How did you define the coordinates for `reg_str` and `reg_str1`?

**Comment by larrybradley** [comment]
Starting from a pixel, you can use `pixel_to_skycoord` (http://docs.astropy.org/en/stable/api/astropy.wcs.utils.pixel_to_skycoord.html) with a WCS object to get the sky coordinates, using either 0- or 1-based coordinates set by the `origin` keyword, e.g.:
```
>>> pixel_to_skycoord(x, y, wcs, origin=0)
```

**Comment by sushobhana** [comment]
for reg_str, the parser defines the coordinate by passing a UnitSphericalRepresentation object to the coordinate frame. Thanks for the info.

**Comment by sushobhana** [comment]
@larrybradley I think the origin is 0 in both cases. The minute differences in the values of both sky coordinates is causing the difference in pixels. 
```
In [56]: a
Out[56]: 
<SkyCoord (FK5: equinox=J2000.000): (ra, dec) in deg
    (24.06237083, 29.93546667)>

In [57]: b
Out[57]: 
<SkyCoord (FK5: equinox=2000.0): (ra, dec) in deg
    (24.06173553, 29.93602756)>

In [58]: a.to_pixel(cube.wcs.celestial, origin=0)
Out[58]: (array(1.52969918), array(2.45944059))

In [59]: b.to_pixel(cube.wcs.celestial, origin=0)
Out[59]: (array(2.5282832), array(3.4612342))

In [60]: c = SkyCoord(np.floor(b.ra),np.floor( b.dec))

In [61]: c.to_pixel(cube.wcs.celestial, origin=0)
Out[61]: (array(86.99324053), array(-1681.73553098))
```
What do you say?

**Comment by sushobhana** [comment]
Makes sense now!! So , the parser should correct the offset. @larrybradley thanks for the clarification.

**Comment by larrybradley** [comment]
@sushobhana  Thanks for catching this discrepancy!
