### ISSUE TITLE
EllipsePixelRegion Angle argument is in radians, not degrees

### ISSUE THREAD

**Issue by cmcclellan1010** [astropy/regions#189]
When defining an EllipsePixelRegion, the angle argument is specified in degrees, but performs rotations as if it is in radians. 

For example:
`EllipsePixelRegion(center, major_axis, minor_axis, angle=90*u.deg)` returns an ellipse with a rotation angle of 90 _radians_.
`EllipsePixelRegion(center, major_axis, minor_axis, angle=1.57*u.deg)` returns an ellipse with a rotation angle of 90 degrees (1.57 radians).

**Comment by joleroi** [comment]
I think this is a bug in the latest stable ``regions`` release (v0.2)

https://github.com/astropy/regions/blob/v0.2/regions/shapes/ellipse.py#L126

In the HEAD version this is fixed, the angle is correctly passed in ``rad`` and everything seems fine

https://github.com/astropy/regions/blob/master/regions/shapes/ellipse.py#L172

```
from regions import EllipsePixelRegion, PixCoord
import astropy.units as u

center = PixCoord(0,0)
major_axis = 200
minor_axis = 100
reg  = EllipsePixelRegion(center, major_axis, minor_axis, angle=45 * u.deg)
mask = reg.to_mask()
plt.imshow(mask.data)
```
![ellipse_region](https://user-images.githubusercontent.com/11678435/41716942-6262331e-7558-11e8-8016-9722d869ab27.png)

@cmcclellan1010 - Is using the development version of ``regions`` an option for you?

**Comment by cmcclellan1010** [comment]
Right you are -- I'll switch over to the development version. Thanks!
