### ISSUE TITLE
Python 3.7 support 

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#206]
@astrofrog @keflavich @sushobhana @bsipocz  - It seems the latest stable regions 0.2 doesn't support Python 3.7 yet? (although Numpy and Astropy seem to support it already)

I tried this:
```
conda create --name issue-1717 numpy==1.14.5 scipy==1.1.0 astropy==3.0.3
pip install regions
```
and got this error:
https://gist.github.com/cdeil/c33b0e6a890ed51954500b4bdc37f01c

Does anyone have time to add a CI build for Python 3.7 and see if there's any issues in regions master?

Would it be OK if we cut a regions 0.3 release now (as soon as Python 3.7 is supported) or do we have to wait for some work to land? Does anyone have time to make the next release?

**Comment by sushobhana** [comment]
@cdeil the problem seems to be with cython here. I tried testing regions with python 3.7 locally and it passes.

**Comment by cdeil** [comment]
@sushobhana - Great!

Could you please send a PR that adds a Python 3.7 CI build, and see if it passes there as well?
I would suggest to start with one Linux build, and only try Windows later.

**Comment by cdeil** [comment]
@sushobhana started a PR in #208 .
Let's continue the discussion there.
Closing this issue.
