### ISSUE TITLE
build_sphinx and build_docs

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#210]
I ran `python setup.py build_docs` here and was confused that the autodoc RST files were generated in `docs/api` and the HTML output in `build/sphinx/html`. Wouldn't it be better to have all generated files go in one folder?

I also see that there's still `build_sphinx` configured here:
https://github.com/astropy/regions/blob/9d1a0bf77e997af19b4393f75d5c0a22d4ad4560/setup.cfg#L1

@bsipocz or anyone -  I thought since a year or two it should only be `build_docs` and `build_sphinx` is the old way that shouldn't be used any more? What would you recommend we do here?

**Comment by cdeil** [comment]
This probably isn't important or still relevant, but @bsipocz - could you please have a look at the description above and comment whether this issue should be closed or some edit should be done?

**Comment by bsipocz** [comment]
Oh, I think I never really figured this out being the dinosaur who still prefers to use `build_sphinx`. Looking at it now.

**Comment by bsipocz** [comment]
OK, right, this is not the issue I had in mind. 

It's possible to move the `api` dir relative to `index.rst` with setting `automodapi_toctreedirnm` in `docs/conf.py`. Moving it to `docs/_build/api` somehow broke all the auto generated intersphinx links though, so I don't think it's worth the hack.

Sadly `build_docs` and `build_sphinx` doesn't understand each others' config so ideally both should be listed in `setup.cfg`. We have added `build_docs` to be a convenience for astronomers not familiar with the standard way of `build_sphinx`, but nevertheless the latter is still the standard way for sphinx setuptools integration, so I would advise against removing it.

**Comment by bsipocz** [comment]
(and currently, for me, everything end up in `docs/_build` rather than in `build/sphinx`. I can't recall what triggered it to be build in the latter nor how/when it went away, but that was the issue I thought about first.)

**Comment by cdeil** [comment]
This is horrible in Python, that there are no standards for tests and docs.
I recently learned a bit of Rust and there it's always simple and the same for any project, see https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html
That's so nice.

If only someone wrote a PEP adding a standard recommended solution for Python...

I see you've added something here: https://github.com/astropy/regions/commit/3f69f368680ed52847bce9d117b1bb690c28cef7#diff-380c6a8ebbbce17d55d50ef17d3cf906R6

So I'll just close this issue now. If there's anything else do to, please re-open.

**Comment by bsipocz** [comment]
Well, retrospect we shouldn't have added `build_docs` just because `build_sphinx` was confusing. Anyway, the plan is to at least remove the deprecation warning. https://github.com/astropy/astropy-helpers/issues/481

I wish to learn Rust, too at some point. Is it indeed as good as people claim it to be?

**Comment by cdeil** [comment]
> I wish to learn Rust, too at some point. Is it indeed as good as people claim it to be?

I don't feel qualified at all to answer that yet. It's not what I expected - I thought it's a simplified and safe C - but really it's a complex language, not something I could learn quickly even though I know Python, C and C++ quite well. But yes, they have a lot of good things, e.g. speed, parallelism, good tools for build and docs and distribution, ...
