### ISSUE TITLE
Metadata has gone missing

### ISSUE THREAD

**Issue by keflavich** [astropy/regions#233]
Sometime in the last few months, the `text` metadata stopped being read from ds9 region files.

**Comment by bsipocz** [comment]
Well, upstream API changes are somewhat bugs, too. But I've removed the label nevertheless :)

**Comment by keflavich** [comment]
no, this isn't an upstream change, it's a change we made here.   I think it was a wrong change.  This is kind of a bug, but more just.... a questionable design decision on our part.
