### ISSUE TITLE
DS9Parser coordinate system

### ISSUE THREAD

**Issue by vtcloud** [astropy/regions#236]
The ds9parser is not handling the mixed or upper case coordinate system entries:

If the coordinate system is, e.g., Galactic or GALACTIC, an error is raised:
     DS9RegionParserError: Region type 'GALACTIC' was identified, but it is not one of the known region types.

Example:
from regions import DS9Parser
reg_string = 'GALACTIC\ncircle(10,10,20) # text={This message has both a " and : in it} textangle=30'
parser = DS9Parser(reg_string)

It only works with full lower case "galactic"!

using regions: regions==0.4.dev0, downloaded from github on 2019/1/22

**Comment by keflavich** [comment]
Is the uppercase version allowed in ds9?  I've never checked whether the format is case-sensitive; I'm not sure it's stated anywhere in the specifications (...or if there even are formal specifications)

**Comment by vtcloud** [comment]
Yes. The following is from the DS9 online help (http://ds9.si.edu/doc/ref/region.html#RegionFileFormat):

If no such system is explicitly specified, the default system is implicitly assumed to be PHYSICAL. In practice this means that for IMAGE and PHYSICAL systems, pure numbers are pixels. Otherwise, for all systems other than linear, pure numbers are degrees. For LINEAR systems, pure numbers are in the units of the linear system. This rule covers both positions and sizes. The input values to each shape can be specified in several coordinate systems including:

    IMAGE                   # pixel coords of current file

    LINEAR                  # linear wcs as defined in file

    FK4, B1950              # sky coordinate systems
    FK5, J2000
    GALACTIC
    ECLIPTIC
    ICRS
    PHYSICAL                # pixel coords of original file using LTM/LTV
    AMPLIFIER               # mosaic coords of original file using ATM/ATV
    DETECTOR                # mosaic coords of original file using DTM/DTV

    WCS,WCSA-WCSZ           # specify which WCS system to be used for
                            # linear and sky coordinate systems

However, I could not find anything about mixed cases although DS9 itself can handle it.

**Comment by keflavich** [comment]
alright, the empirical "ds9 can handle it" is good enough.  We just need to add a `.lower()` somewhere in the parser.

**Comment by vtcloud** [comment]
That's what I expected. Thank you.

**Comment by larrybradley** [comment]
This was fixed in #237.
