### ISSUE TITLE
Drop Python 2 support?

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#241]
I suggest we drop Python 2 support now in regions and only support Python 3.5+.

This is following the lead of Astropy core from last year.

I'm happy to send a PR for `regions` and `astropy-healpix` in the next days.

Looks like there's almost no changes since the last regions 0.3 release, so as far as I can see there's no use in making an 0.4 release before dropping Python 2 support.

@astrofrog @keflavich @sushobhana @larrybradley - Please comment.

**Comment by cdeil** [comment]
@keflavich - Could you please have a look at your open PRs #240, #237, #234, #227 and merge some in, to avoid potential merge conflicts when we drop Python 2?

**Comment by larrybradley** [comment]
I'm +1 for dropping python 2 support and going to 3.5+.

**Comment by keflavich** [comment]
I'm opposed to dropping python 2 support until CASA switches to python3, which should be this year.  Ideally, I'd like to have CASA tests of the CRTF module, and since CASA is still python2 for now, those tests won't be possible until CASA switches to python3.

Also, I'm totally booked out for the next few weeks, but I will revisit this.  Ping me again.

**Comment by cdeil** [comment]
Bummer.

@bmatthieu3 would like to add MOC regions (see PR #219), which is based on `astropy-healpix`, and there we wanted to go ahead and drop Python 2 support now (see https://github.com/astropy/astropy-healpix/pull/125) and in the coming months develop the package further in `master` to a state where eventually it can be proposed for the core package as `astropy.healpix`, and then `astropy.regions` would follow.

@keflavich - Is a stable `regions=0.4` branch that supports Python 2.7 where you can keep putting fixes and features for CRTF / CASA users for as long as you like an option? That would allow `master` to move ahead.

If no, OK, I'll discuss with @bmatthieu3 and we'll find a solution to move ahead with `astropy-healpix` and MOC regions development under the constraint that `astropy-regions` remains Python 2 compatible for the next ~ year.

**Comment by keflavich** [comment]
I think we can live with a regions=0.4 pre-healpix version that remains backward compatible.  It's a bit of a headache to track if we actually add features, but that's not the end of the world.

**Comment by bsipocz** [comment]
> I suggest we drop Python 2 support now in regions and only support Python 3.5+.

Any reasons not to go straight to 3.6+?

**Comment by cdeil** [comment]
> Any reasons not to go straight to 3.6+?

Was suggested by @astrofrog in https://github.com/astropy/astropy-healpix/issues/111#issuecomment-460215582 :

> I'd say `>=3.5` unless you have a good reason to go `>=3.6` (basically I think it makes sense to stay in line with astropy core).

I guess there are Linux distros that shipped Python 3.5 in the past years and some fraction of users has that as a basis, so makes sense to wait a year or two for Python 3.6 and putting f-strings, no?

**Comment by bsipocz** [comment]
Fair enough. Astropy will drop it this fall in 4.0, so if you plan to have releases before that, it can makes sense to keep it in.

**Comment by bsipocz** [comment]
Fair enough. Astropy will drop it this fall in 4.0, so if you plan to have releases before that, it can makes sense to keep it in.

**Comment by keflavich** [comment]
I'm now :+1: on removing py2 support in the next release.

**Comment by bsipocz** [comment]
next release you mean v0.5 or v0.6?

**Comment by keflavich** [comment]
Closed by #291
