### ISSUE TITLE
Mask.multiply seems not to apply "fill_value"

### ISSUE THREAD

**Issue by bersavosh** [astropy/regions#242]
Hi,

I've been trying to apply a mask to some data with the requirement that the data pixels outside the mask be a certain value (in this specific case "nan"). I've been trying to use `fill_value` for this, however the output with non-zero `fill_value` seems to be identical to output with the default case (`fill_value=0`).

I've prepared a [Jupyter notebook](https://github.com/bersavosh/Random/blob/master/regions_fill_value_demo.ipynb) demonstrating the issue. I'm not sure if this is an issue with the Mask, or me misunderstanding the purpose of `fill_value`. I apologise if it is the latter. 

thanks,
Arash

**Comment by nitish705702** [comment]
Sir i am interested for in this project , please guid me.

**Comment by cdeil** [comment]
@bersavosh - Thanks for reporting the issue and for preparing https://nbviewer.jupyter.org/github/bersavosh/Random/blob/master/regions_fill_value_demo.ipynb .

@keflavich - Can you have a look? Does this need a docs or code change? Is #272 related?

**Comment by keflavich** [comment]
@larrybradley We need clarification in the docs that `fill_value` presently only refers to regions that partially overlap the image.  We also do want to be able to specify the value of the out-of-region area within the bounding box; that presently is hard-coded to zero.
