### ISSUE TITLE
Astropy/Region Tutorial "Computing Overlap Masks" error

### ISSUE THREAD

**Issue by Vab-jain** [astropy/regions#245]
In the "Computing Overlap Masks" [tutorial,](https://astropy-regions.readthedocs.io/en/latest/masks.html) the example to demonstrate different `to_mask()` modes does not show the plot due to missing `plt.show()` command.
![tut_error](https://user-images.githubusercontent.com/22465402/54084132-d74c6c80-4352-11e9-8a4b-c3de4b398fab.png)

Here is a fixed version of it.
![tut_fix](https://user-images.githubusercontent.com/22465402/54084155-2db9ab00-4353-11e9-91ff-dce295bb6d98.png)

Similar error is also there in the next example of `to_image()` method

**Comment by keflavich** [comment]
This is a user settings issue.  If you set `pl.ion()`, the images will display.
