### ISSUE TITLE
PolygonSkyRegion in AITOFF: problem for truncated regions

### ISSUE THREAD

**Issue by vfioretti** [astropy/regions#254]
Dear Astropy/regions developers,

when creating a Polygonal region in galactic coordinates (both using PolygonSkyRegion or PixCoord.from_sky and the WCS library), if the coordinate points cross the 180 degree longitude border then the method fails and it gives a wrong region. It seems that the method sees the region as two truncated regions and it tries to unify them.
The bug came out when creating the Polygon region and then searching, from a set of healpix pixel positions, which positions are contained in the region.

I attach the image with the contour (black line) from which a created a region, and the healpix position (small black rings) that should be contained in the region.

Am I doing something wrong?

Here the base code that I am using:
`hdulist = fits.open(map)`
 `w = wcs.WCS(hdulist[0].header)`
`skycoord = SkyCoord(points[0],points[1], unit='deg', frame='galactic')`
`polygon_sky = PolygonSkyRegion(vertices=SkyCoord(l=contour[0], b=contour[1], unit='deg', frame='galactic'))`
`coordinate_check = polygon_sky.contains(skycoord, w)`

Thanks a lot for your help.
Valentina

![case4_problem](https://user-images.githubusercontent.com/4559399/56138814-e8168080-5f97-11e9-8e9a-97bc7d514ab3.png)

**Comment by larrybradley** [comment]
This appears to be the same issue as #150.
