### ISSUE TITLE
Release regions v0.4

### ISSUE THREAD

**Issue by bsipocz** [astropy/regions#261]
@cdeil @larrybradley @keflavich - `regions` will start to raise DeprecationWarnings when used with astropy v3.2. 
Given it's a coordinated package, I think it would be beneficial to avoid this by doing a new release __now__ either calling it 0.3.1 or 0.4 rather than waiting longer to get more features in.

**Comment by cdeil** [comment]
I can cut a v0.4 release tomorrow. If someone wants to wait and get something in, SHOUT NOW!

There probably aren't many developments, but #225 is fixed, six is listed as a dependency now, avoiding pip install errors, and in #258 astropy-healpix as a dependency was removed, and making `regions` independent from `astropy-healpix` lets use move ahead there and drop Python 2 support. So 0.4 is mostly a "dependency fixes" release.

**Comment by bsipocz** [comment]
Thank you!

**Comment by bsipocz** [comment]
If there is anything to help with, pls ping me, should be around tomorrow.

**Comment by larrybradley** [comment]
@cdeil Please include #277 and #278!

**Comment by cdeil** [comment]
I updated the changelog in d5e1c7c , will proceed and release v0.4 now.

If some important point is missing in the changelog, please just add it via a commit in master any time.

I also set a milestone for all issues and PRs on Github based on the dates of previous releases, and added a link to those lists from the changelog. That should make it easier to see what was in which release.

**Comment by cdeil** [comment]
https://pypi.org/project/regions/0.4/

**Comment by cdeil** [comment]
https://github.com/astropy/regions/releases/tag/v0.4

**Comment by cdeil** [comment]
Docs are ready: https://astropy-regions.readthedocs.io/en/v0.4/changelog.html

**Comment by cdeil** [comment]
Does anyone think we should send a short announcement email for regions v0.4 to astropy-dev?
(I'm not sure it's useful, but if you think so, we can)

**Comment by bsipocz** [comment]
Yes, I think it's nice to send release announcements to the list. I know we didn't do it consistently in the past, but nevertheless it's a nice heads up (e.g. maintainers of astroquery can go ahead and remove workarounds, but we might not be alone who did that).

**Comment by cdeil** [comment]
Conda packages are done:
- https://anaconda.org/conda-forge/regions/files
- https://github.com/conda-forge/regions-feedstock/pull/9

**Comment by cdeil** [comment]
> I think it's nice to send release announcements to the list. 

Done:  https://groups.google.com/forum/#!topic/astropy-dev/0e5l8VL3v7A

I'm closing this issue and the v0.4 milestone.

On to v0.5!
