### ISSUE TITLE
Add region rotate method

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#265]
We would like to add a method to the region classes to rotate around a given point by a given angle.

This is needed in Gammapy, because in ground-based gamma-ray astronomy one common background estimation technique is to point off-source (called "wobble offsets") and to estimate the background in a given "on" or "source" region from "off" regions which are rotated around the pointing position, following the good assumption that background in the field of view is rotationally symmetric.

This is illustrated [here](https://docs.gammapy.org/0.12/background/reflected.html) and already implemented in Gammapy in the [ReflectedRegionsFinder](https://docs.gammapy.org/0.12/api/gammapy.background.ReflectedRegionsFinder.html), but it turns out that computing rotated regions for different shapes is difficult, it leads to if, else, getattr.

It would be much simpler to implement this as
```
rotated_region = region.rotate(point, angle)
```
and to have `rotated_region` be an independent new object with some attributes changed (like e.g. center and angle for a rectangle).

@astrofrog @keflavich - OK if we add this method?

The added method doesn't interfere with the rest of the regions code, and we promise to add tests and maintain it.

There are some details to be worked out, the most important question probably being whether this is added only for pixel regions (what we currently use for this in Gammapy), or in addition also for sky regions (what we might want to use in Gammapy). Another question is if all regions support this or not, i.e. if this should be a required method via the `PixRegion` ABC, or just added to the regions that do support it. These things will become clear once we start to implement it...

**Comment by keflavich** [comment]
Huge :+1: from me.  I think we need this functionality if and when we make a region editor gui

**Comment by cdeil** [comment]
Just to be clear: there is an option to implement this feature by adding a `rotation_center` and `rotation_angle` data member to region objects, and then to apply rotations on the fly in contains and draw and other operations. I've seen this in one (non-public) gamma-ray code, and I think such a "transform" feature is also sometimes used in graphics programs.

My suggestion here was to **not** do that, but just to add a method that makes a copy, then modifies the exiting data members like `center` or `angle`, and returns the new object.

So if anyone thinks it should be implemented in a different way, please comment here.

**Comment by keflavich** [comment]
I think your approach would make the GUI editing a little more difficult.  I agree generally that it's the better thing to do, but please keep in mind that we may _internally_ want editable objects.

**Comment by cdeil** [comment]
Implemented in #281 and #285
