### ISSUE TITLE
Example breaks windows testing

### ISSUE THREAD

**Issue by bsipocz** [astropy/regions#267]
#263 has enable doctests and as a result the appveyor build is complaining file access error as it's being used by another process. (The weird thing is that all tests pass, so it would be nice to be able to turn this strictness off).

The workaround I ended up with is to allow the failures of the appveyor jobs to let the release procedure for 0.4 proceed.

cc @pllim @astrofrog @saimn as you are the ones who solved similar issues in astropy before.

```
============= 955 passed, 8 skipped, 13 xfailed in 35.62 seconds ==============
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\conda\envs\test\lib\site-packages\astropy\utils\decorators.py", line 860, in test
    func = make_function_with_signature(func, name=name, **wrapped_args)
  File "C:\conda\envs\test\lib\site-packages\astropy\tests\runner.py", line 260, in test
    return runner.run_tests(**kwargs)
  File "C:\conda\envs\test\lib\site-packages\astropy\tests\runner.py", line 605, in run_tests
    return super().run_tests(**kwargs)
  File "C:\conda\envs\test\lib\site-packages\astropy\tests\runner.py", line 242, in run_tests
    return pytest.main(args=args, plugins=plugins)
  File "C:\conda\envs\test\lib\site-packages\astropy\config\paths.py", line 182, in __exit__
    shutil.rmtree(self._path)
  File "C:\conda\envs\test\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\conda\envs\test\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\conda\envs\test\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\conda\envs\test\lib\shutil.py", line 392, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\conda\envs\test\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\conda\envs\test\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmppexf4t80astropy_cache\\astropy\\download\\py3\\2c9202ae878ecfcb60878ceb63837f5f'
```

**Comment by pllim** [comment]
I remember seeing it but I don't remember any solution. It is how Windows deals with the file pointer differently *(insert mystery music)*, causing this message. If others remember a solution, please chime in.

**Comment by pllim** [comment]
I found something here -- not sure if it is a solution for you, but apparently Past Me ™️ fixed it by caching.

https://github.com/astropy/astropy/issues/7757#issuecomment-415592313

**Comment by pllim** [comment]
Also maybe try `memmap=False` if it is FITS file. xref astropy/astropy#7404

**Comment by bsipocz** [comment]
Yes, I've tried the solution from astropy/astropy#7757, it had no effect (haven't tried memmap). Do you also think it's the fits files that cause the problem?
Honestly I run out of steam of sorting windows out, anyone is more than welcome to grab this and run with it.

**Comment by cdeil** [comment]
If I run the tests twice I now get this error:
```
_______________________________________________________________________ [doctest] regions.io.fits.write.write_fits_region _______________________________________________________________________
063     Examples
064     --------
065 
066     >>> from astropy.utils.data import get_pkg_data_filename
067     >>> from astropy.io import fits
068     >>> file_sample = get_pkg_data_filename('data/fits_region.fits', package='regions.io.fits.tests')
069     >>> from regions import CirclePixelRegion, PixCoord, write_fits_region
070     >>> reg_pixel = CirclePixelRegion(PixCoord(1, 2), 5)
071     >>> hdul = fits.open(file_sample)
072     >>> write_fits_region('region_output.fits', regions=[reg_pixel], header=hdul[1].header)
UNEXPECTED EXCEPTION: OSError("File 'region_output.fits' already exists.")
Traceback (most recent call last):

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/doctest.py", line 1329, in __run
    compileflags, 1), test.globs)

  File "<doctest regions.io.fits.write.write_fits_region[6]>", line 1, in <module>

  File "/Users/deil/work/code/regions/regions/io/fits/write.py", line 78, in write_fits_region
    bin_table.writeto(filename)

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py", line 1543, in writeto
    checksum=checksum)

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 919, in writeto
    fileobj = _File(fileobj, mode=mode, overwrite=overwrite)

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/site-packages/astropy/io/fits/file.py", line 178, in __init__
    self._open_filename(fileobj, mode, overwrite)

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/site-packages/astropy/io/fits/file.py", line 544, in _open_filename
    self._overwrite_existing(overwrite, None, True)

  File "/Users/deil/software/anaconda3/envs/regions/lib/python3.7/site-packages/astropy/io/fits/file.py", line 438, in _overwrite_existing
    raise OSError("File {!r} already exists.".format(self.name))

OSError: File 'region_output.fits' already exists.

/Users/deil/work/code/regions/regions/io/fits/write.py:72: UnexpectedException
```

The problem is that that doctest writes to the current working directory.
That's no good.

Personally I don't like doctests at all, and my suggestion would be to simply skip that example and not run it as a doctest. But probably another course of action could be to try and configure it somehow to run in a temp folder?

@pllim @bsipocz - Thoughts?

**Comment by bsipocz** [comment]
> Personally I don't like doctests at all, and my suggestion would be to simply skip that example and not run it as a doctest. But probably another course of action could be to try and configure it somehow to run in a temp folder?

Personal dislikes here I don't think count. We shouldn't have examples in the docs that are not guaranteed to run. I would  be much more comfortable removing the examples than skipping testing them.

So I agree that the test should be fixed either to write to a temp file, or to remove the writing part of it. Sadly I don't have time to work on regions in the near future.

**Comment by cdeil** [comment]
There's three doctests that write to an output file in the CWD, and that fail when one runs the tests via `pytest regions`:
```
	region_output.fits
	test_write.crtf
	test_write.reg
```
@pllim - I'll wait to see what you come up with in #268 , but probably that's unrelated, and then I could make a PR which fixes the doctests somehow. What is a good way? `import tempfile` in examples users read is not great. Is there a better way?

**Comment by pllim** [comment]
@cdeil , why not add an `overwrite` option to the API instead?

https://github.com/astropy/regions/blob/66ab0cdf40be23b2c72b23bcfbe64a9a06db9452/regions/io/fits/write.py#L50

Your problem here will not be solved with my PR to debug Windows file error.

**Comment by bsipocz** [comment]
@cdeil - why did you reopen this? Appveyor is all green now.

**Comment by cdeil** [comment]
@bsipocz - I re-opened because I wanted to resolve the remaining issue discussed here. Posted my suggestion in #273 .

> We shouldn't have examples in the docs that are not guaranteed to run. I would be much more comfortable removing the examples than skipping testing them.

In #273 I removed them. I'm not sure why the equivalent docs examples in the `docs` folder don't create temp files in the CWD. Maybe they aren't picked up?

I really think insisting to run all examples as tests is too much. Good examples don't make for good tests, and IMO putting `import tempfile` isn't appropriate for end-user examples. See e.g. http://docs.astropy.org/en/stable/table/io.html - you'll find a `doctest-skip-all` at the top, and similarly in many places where in the Astropy docs examples files are written, those examples are not executed as doctests.

**Comment by bsipocz** [comment]
yes, and we're having issues from time to time that those examples are breaking which is both embarrassing and stressful. It's rather a nightmare really to keep on top of the examples working as they suppose to work if they are not tested. I agree that they are not good unit tests, but excellent integration tests 😉

**Comment by bsipocz** [comment]
(And tests in http://docs.astropy.org/en/stable/table/io.html  arguably are skipped (just as in the whole of astroquery) as we don't have a crucial piece of infrastructure to support better setup for examples that require remote data access, see the long standing issue of https://github.com/astropy/pytest-doctestplus/issues/2 and it's precursors)

**Comment by cdeil** [comment]
Disagree that doctests are good integration tests. A good test always has asserts at the end. A docs example never has asserts at the end. Sometimes you can get away by printing something, but in the case of I/O functions like here, the deficiencies of doctests really become clear.

I do agree that executing docs examples is valuable to have easier-to-maintain docs. But when it's not possible to have both (good simple example, and doctest), I prefer to keep the good simple example and to not have it tested.

**Comment by bsipocz** [comment]
Well, my PR showed that many of these simple examples were broken, and many with Syntax Error. While I hear your point about simple examples, I think for a multi people project all examples needs to be tested to keep things consistent.
