### ISSUE TITLE
setup.py should define python_requires

### ISSUE THREAD

**Issue by astrofrog** [astropy/regions#280]
Currently we don't specify which versions of Python we are compatible with - this should be done with ``python_requires`` in ``setup.py`` (or in ``setup.cfg`` if using that)

**Comment by cdeil** [comment]
For now it should be "2.7 or 3.5+" (see #241)
@astrofrog or @bsipocz  - Probably you know how to put that in `setup.py` and/or `setup.cfg`?
Would you mind doing it (directly as a commit in master if you like)?

**Comment by larrybradley** [comment]
Added in https://github.com/astropy/regions/pull/282.
