### ISSUE TITLE
Release regions v0.5

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#292]
I suggest we do a regions v0.5 release on July 23. Alternatively I could do one on August 12 after vacation. We can use this issue to discuss release date and who does what a bit.

There's several bugs we should fix, and some features we'd like to add:
https://github.com/astropy/regions/milestone/7

Nothing is super-urgent, but maybe frequent regions releases every month or two can motivate us to work on it and move forward.

**Comment by larrybradley** [comment]
Regions v0.5 is released.
