### ISSUE TITLE
Plotting API

### ISSUE THREAD

**Issue by larrybradley** [astropy/regions#296]
Currently the `plot` method for the region classes returns the `matplotlib.Axes.axes` instance on which the region patch is added.  This makes adding a plot legend a bit cumbersome.  One cannot use the `plot` method for this case.  Instead, one must create the patch objects and then add them to the plot like this:

```python
from regions import PixCoord, CirclePixelRegion
reg1 = CirclePixelRegion(PixCoord(3, 3), radius=1.5)
reg2 = CirclePixelRegion(PixCoord(5, 5), radius=2.5)
data = np.ones((11, 11))

plt.imshow(data, cmap='Greys')
patches = [reg1.as_artist(color='red', label='Region A'),
           reg2.as_artist(color='blue', lw=3, label='Region B')]
ax = plt.gca()
for patch in patches:
    ax.add_patch(patch)
ax.legend(handles=patches)
```

Instead, if the `plot` method were to return a `matplotlib.patches.Patch` object, one could do:

```python
from regions import PixCoord, CirclePixelRegion
reg1 = CirclePixelRegion(PixCoord(3, 3), radius=1.5)
reg2 = CirclePixelRegion(PixCoord(5, 5), radius=2.5)
data = np.ones((11, 11))

plt.imshow(data, cmap='Greys')
patch1 = reg1.plot(color='red', label='Region A')
patch2 = reg2.plot(color='blue', lw=3, label='Region B')
patches = [patch1, patch2]
ax.legend(handles=patches)
```

This seems more intuitive given that the `matplotlib` `plot` method returns the Artist (i.e. `matplotlib.lines.Line2D`) that was plotted.

Why does the region `plot` method return an Axes instance, which will either be `plt.gca()` or simply the `ax` value that was input to the plot function (which is useless)?  What is the use case here?  Thoughts?

This case up in a PR submitted to `photutils`:  https://github.com/astropy/photutils/pull/923.  I would like to have the `photutils` aperture API be (somewhat) consistent with the `regions` shape API. 

CC:  @keflavich, @astrofrog, @cdeil

**Comment by larrybradley** [comment]
Another plotting API question I have is why `as_artist` instead of `to_artist`?  It's not a view of the region as an artist, it's converting a region to a patch (artist).

For example, we have `to_pixel` and `to_sky` methods to convert region objects.

**Comment by keflavich** [comment]
`to_pixel` and `to_sky` return region objects, `as_artist` returns a different type of object, so I think this choice was to distinguish between those.  But I'm not sure.

I like the idea of having `plot` return the patch; that's more consistent w/matplotlib apis

**Comment by cdeil** [comment]
@larrybradley - I think your suggestions are good ones, we should make those changes.

Possibly this pattern to return `ax` was introduced by me, we also have it everywhere in Gammapy, with the idea that this would make it easier for users to get a hold of the `ax` object and e.g. customise it. I guess if we don't return it, users would have to call `plt.gca()`, right?
If that's the more standard pattern for MPL functions, OK to change to that pattern and (never?) return `ax`.

Possibly related question: is the pattern to take an `ax=None` argument and to call `ax = plt.gca() if ax is None else ax` in plotting methods good? I just noticed a case in Gammapy where this `plt.gca()` doesn't yield a new axis like I want, but an axis from an unrelated plot in a previous cell in a Jupyter notebook (see [here](https://github.com/gammapy/gammapy/pull/2435#issuecomment-538326363)). I guess this pattern is still the best one can do, and one just has to teach users to put a `plt.figure()` or `plt.subplots()` call always at the start when making a new plot?

@adonath - Thoughts?

**Comment by astrofrog** [comment]
I think the use of ``to_`` was to emphasize conversion of the actual values whereas ``as_`` was to represent it as a different kind of object, but if that's confusing we could just use ``to_`` throughout.

+1 on returning patches from ``plot``

**Comment by adonath** [comment]
Just for completeness, here is the plotting example with the current API, how I would typically use it:
```python3
from regions import PixCoord, CirclePixelRegion
import numpy as np
import matplotlib.pyplot as plt

reg1 = CirclePixelRegion(PixCoord(3, 3), radius=1.5)
reg2 = CirclePixelRegion(PixCoord(5, 5), radius=2.5)
data = np.ones((11, 11))

ax = plt.subplot()
ax.imshow(data, cmap='Greys')
reg1.plot(ax=ax, color='red', label='Region A')
reg2.plot(ax=ax, color='blue', lw=3, label='Region B')
ax.legend(handles=ax.artists)
```
In gammapy we typically have the part where the axis is created and the subsequent call to `.imshow()` within the `.plot()` method and then the `Axis` or `WCSAxis` is returned, so that it can be used for further plotting. So the `.plot()` method is used to create a meaningful default plot, that can be extended / modified by the user after.

In the current implementation of the `PixelRegion.plot()` method I agree it is not super-useful to return the axis, especially because `reg1.plot()` does not plot anything on its own.

The only alternative path (I'm not really proposing it, just mentioning it for completeness...) is to modify `PixelRegion.plot()` to plot on an empty image (e.g. based on the bounding box) to illustrate the region by default. So that the following example would work:
```python3
from regions import PixCoord, CirclePixelRegion

reg1 = CirclePixelRegion(PixCoord(3, 3), radius=1.5)
reg2 = CirclePixelRegion(PixCoord(5, 5), radius=2.5)

ax = reg1.plot(color='red', label='Region A')
reg2.plot(ax=ax, color='blue', lw=3, label='Region B')
ax.legend(handles=ax.artists)
```
But I'm not sure whether it's useful, because in 98% of the cases you want to plot the region on top of an existing sky image and not an empty one, so the actual use-cases are very limited...

**Comment by cdeil** [comment]
@adonath - Thanks!

@larrybradley - You decide.

Let me know if I should send a PR or if you want to do it.
I have some time for regions in the coming weeks.
