### ISSUE TITLE
to_mask method

### ISSUE THREAD

**Issue by larrybradley** [astropy/regions#30]
I think the `to_mask` method needs to have an input `shape` parameter to define the shape of the output mask image (which presumably would be the same as the `data` image):
https://github.com/astropy/regions/blob/master/regions/core/core.py#L135

Or am I missing something?

**Comment by astrofrog** [comment]
At pyastro17, we discussed this and we think it would be more useful to return (by default) an object that consists of a minimal mask with an origin, then provide functions that can apply it to arrays. The reason is that for example if I want to extract a small mask to apply to a star in an 8k by 8k image, I should never have to create an 8k by 8k mask.

**Comment by larrybradley** [comment]
Nevermind, I see the returned `slice` objects now, so I assume you intend that the `to_mask` method returns a "cutout" array only where the mask in non-zero and the returned slices allow you to select the same cutout region from your data.  Is that right?

**Comment by larrybradley** [comment]
That makes complete sense.  I didn't see the `slice` returns initially.

I'm currently working on updating the `photutils` aperture masks.

**Comment by larrybradley** [comment]
There will need to be some machinery somewhere to handle the cases where the region is near the edge (partially on the data) or completely outside of the data.  The returned `slices` in those cases will be "wrong".

**Comment by bsipocz** [comment]
@astrofrog - surely you meant pyastro16 :wink:

**Comment by larrybradley** [comment]
I assumed that @astrofrog is a time traveler and reporting on future events.... 😃

**Comment by astrofrog** [comment]
![68739916](https://cloud.githubusercontent.com/assets/314716/15875847/f22905b4-2d01-11e6-9932-d1350c6f5f6b.jpg)
