### ISSUE TITLE
GUI regions editor

### ISSUE THREAD

**Issue by keflavich** [astropy/regions#308]
It would be extremely helpful to have a matplotlib region editing interface to add, remove, and reshape regions.  AFAIK, we don't have this now, though some affiliated packages (e.g., https://github.com/astropy/regions/issues/69) provide some of this functionality.  Such editors would be useful for:

1. Dropping photometry apertures
2. Creating interactive CLEAN masks (radio application)
3. Creating serializable "brushing" regions (e.g., for Glue)

**Comment by larrybradley** [comment]
The current status of outstanding work on interactive regions is captured in #391.
