### ISSUE TITLE
write_crtf and CASA 5.6

### ISSUE THREAD

**Issue by JonahDW** [astropy/regions#312]
I'm facing some issues writing regions to a CRTF file with `write_crtf` and having CASA interpreting them. I'm using CASA 5.6, a newer version than for which the software was probably written.

I'm writing ellipses to a file, where a single line of the written file looks like:
`ellipse[[279.174990deg, -21.257123deg], [0.001571deg, 0.001973deg], 111.273322deg], coord=FK5,`

This causes an error when passing the mask to tclean in CASA
```
2020-05-11 12:30:29     SEVERE  task_tclean::SDMaskHandler::regionTextToImageRegion (file ../../synthesis/ImagerObjects/SDMaskHa
ndler.cc, line 490)     Exception: Exception: ../Reduction_scripts/ARTIP/J1833_mask.crtf line# 2: Illegal extra characters on li
ne (). Did you forget a '='?.
2020-05-11 12:30:29     SEVERE  task_tclean::SDMaskHandler::regionTextToImageRegion (file ../../synthesis/ImagerObjects/SDMaskHa
ndler.cc, line 490)+    ... thrown by static casa::RegionTextParser::ParamSet casa::RegionTextParser::getParamSet(casacore::Bool
&, casacore::LogIO&, const casacore::String&, const casacore::String&, const casacore::CoordinateSystem&, std::shared_ptr<std::p
air<casacore::MFrequency, casacore::MFrequency> >, std::shared_ptr<casacore::Vector<casacore::Stokes::StokesTypes> >) at File: .
./../imageanalysis/IO/RegionTextParser.cc, line: 589

```
I suspect the trailing comma might be the culprit, I suppose CASA is using a somewhat different way of reading the region file in this version than earlier ones.

**Comment by keflavich** [comment]
I'm pretty sure you're right that the trailing comma is the issue.  I think this is a problem independent of CASA version.  I thought we had dealt with this previously, but it's a clear bug.

**Comment by keflavich** [comment]
Do you have a MWE we could produce this from?  I suppose we can just read in the CRTF and try writing it back out, but how did you make this region?

**Comment by JonahDW** [comment]
I'm making the regions from an input catalog (of radio sources), and then writing them to a CRTF file. I could give you a MWE but all the data involved is proprietary, so you'd have to try this out on your own data if you can.

**Comment by JonahDW** [comment]
If it helps, attached is a small example CRTF file generated by the code. Simply remove the .txt extension (github wouldn't accept the file format) and you're good to go.
[test_mask.crtf.txt](https://github.com/astropy/regions/files/4614092/test_mask.crtf.txt)

**Comment by JonahDW** [comment]
I've spent some time digging into the code, and I've managed to solve some the issues I mentioned here (as well as some other that popped up while testing). I'll be glad to put in a pull request if that saves time for you guys working on this.

**Comment by keflavich** [comment]
Please do, that would be extremely helpful!

**Comment by JonahDW** [comment]
Well, this has all been resolved by now, so I'll close this.
