### ISSUE TITLE
Matplotlib properties should not default to DS9 style

### ISSUE THREAD

**Issue by astrofrog** [astropy/regions#316]
While reviewing the code today, I found the following on the base region class:

```python
    def mpl_properties_default(self, shape='patch'):
        """
        This sets the default values of the visual attributes as specified
        under DS9 convention.
        """

        kwargs = dict()
        kwargs['color'] = self.visual.get('color', 'green')
        kwargs['label'] = self.meta.get('label', "")

        if shape == 'text':
            kwargs['family'] = self.visual.get('font', 'helvetica')
            kwargs['rotation'] = self.visual.get('textangle', '0')
            kwargs['size'] = self.visual.get('fontsize', '12')
            kwargs['style'] = self.visual.get('fontsyle', 'normal')
            kwargs['weight'] = self.visual.get('fontweight', 'roman')

        else:
            if shape == 'Line2D':
                kwargs['marker'] = self.visual.get('symbol', 'o')
                kwargs['markersize'] = self.visual.get('symsize', 11)
                kwargs['markeredgecolor'] = kwargs['color']
                kwargs['markeredgewidth'] = self.visual.get('width', 1)
            if shape == 'patch':
                kwargs['edgecolor'] = kwargs.pop('color')
                kwargs['fill'] = self.visual.get('fill', False)

            kwargs['linewidth'] = self.visual.get('linewidth', 1)
            kwargs['linestyle'] = self.visual.get('linstyle', 'solid')
```

I found it strange that we should default to the DS9 defaults - I would expect by default that we would default to the default matplotlib styles for text and patches and so on. DS9 is just one of several formats we support.

There are I think two solutions to make this cleaner:
 
**Option 1:** Provide a DS9-specific style sheet for matplotlib that users can opt in to via the regular rc parameter/style infrastructure. This requires users to know how to set this properly though.

**Option 2:** Add a kwarg to ``as_artist`` to specify the style to use, with options of 'default' (meaning matplotlib defaults) and 'ds9', and with the option to add more styles in future.

**Option 3:** only use the DS9 visual defaults if reading from a DS9 region file. I don't like this too much since I think users really should be able to easily choose what styling they want irrespective of where the region came from.

Alternatively, we could also create a ``ScienceState`` for the default style to use which can then be set via the standard astropy configuration machinery.

@larrybradley @keflavich - any thoughts on this?

**Comment by keflavich** [comment]
I'd be happy to have stylesheets, or something like that, but the ds9 defaults are much more reasonable than the matplotlib defaults.  Especially this: 
```
                kwargs['fill'] = self.visual.get('fill', False)
```
Defaulting to filled regions is not a sensible default for what we mean by "regions" in this package.  

Everything else, I'm totally agnostic on, and we probably just picked these defaults as comfortable ones or well-enumerated ones.  I don't know what the mpl defaults are for anything except the facecolor, which is filled and therefore, in my standard use case, unusable.

**Comment by keflavich** [comment]
My stance right now is that mucking with the defaults is a low priority.

**Comment by astrofrog** [comment]
Just FYI, The reason it came up is because Helvetica is actually not properly supported as a font for Matplotlib on all platforms, so it's possible some users would have issues there. At some point if I have time I may look into improving all this but I agree it's not the highest priority!

**Comment by larrybradley** [comment]
I agree that the default styles should not be DS9 and that we should go with the default matplotlib style -- except for the fill option, which I agree with @keflavich should be False.  That is exactly what I do for the photutils apertures (mpl defaults, except fill=False).  I like the DS9 stylesheet option, but we will need to document it so users know how to use it.

**Comment by dhomeier** [comment]
The entire function has been renamed in 54b8089, right – maybe this should be noted in `CHANGES`?

**Comment by larrybradley** [comment]
I didn't add to the change log because I really doubt anyone is calling this function (it's an internal implementation detail).  I searched GitHub and didn't find any usage.  Given the low likelihood and the fact that we advertise on the main doc page that the API is not stable, I didn't think this change was necessary for the change log.

I'm actually working on this exact issue of dealing with mpl defaults.  PR coming soon.

**Comment by dhomeier** [comment]
Probably reasonable, since it is now private. I just stumbled over this issue as I wanted to check if or where the plotting styles were changed from the matplotlib defaults in any way, and then could not find any occurrence of `mpl_properties_default` except in the changelog, where it is documented as been introduced, but never marked as removed.
