### ISSUE TITLE
Region editor wishlist

### ISSUE THREAD

**Issue by keflavich** [astropy/regions#323]
Followup to #317 

- [ ] Each region in a list should be editable
- [ ] Activate region selector on click
- [ ] Allow multiple region selection / deselection
- [ ] Allow bulk region movement

**Comment by keflavich** [comment]
#317 is merged.   Todo items from that:
 * [ ] Expand approach to other region types
 * [ ] Investigate how to deal with Sky regions and WCSAxes
 * [ ] Improve Matplotlib selectors to support e.g. rotation (could potentially be done as part of another PR since we can just raise a NotImplementedError in the mean time)
 * [ ] Documentation

**Comment by keflavich** [comment]
Have we solved:
 * [ ] Create a new region by clicking (region initialization)

**Comment by keflavich** [comment]
Related Matplotlib PRs that enable some of the above:


Rotation:
https://github.com/matplotlib/matplotlib/pull/19853
https://github.com/matplotlib/matplotlib/pull/19864 

Selection:
https://github.com/matplotlib/matplotlib/pull/19657 

Polygon vertex addition/removal:
https://github.com/matplotlib/matplotlib/pull/19660

**Comment by larrybradley** [comment]
The current status of outstanding work on interactive regions is captured in #391.
