### ISSUE TITLE
Drop Python 3.6 support?

### ISSUE THREAD

**Issue by larrybradley** [astropy/regions#340]
Can we drop Python 3.6 support?  @keflavich, @astrofrog ?

**Comment by keflavich** [comment]
I'd prefer not to until CASA6 moves to >3.6.  Is there anything in >=3.7 we need?

**Comment by larrybradley** [comment]
OK, thanks.  I was hoping to drop 3.6 to 1) simplify the CI matrix and 2) be consistent with astropy core (and other packages that have adopted NEP-29; https://numpy.org/neps/nep-0029-deprecation_policy.html) so we can move regions into astropy.regions.

Do you know when CASA6 will be Python 3.7+?  We won't be able to move regions to astropy core until we drop Python 3.6.  Python 3.6 is EOL Dec 23, 2021.

**Comment by larrybradley** [comment]
I'd really like to get regions into astropy for 5.0 (feature freeze 10/29/2021).

**Comment by keflavich** [comment]
I'm happy to set astropy 5.0 as a goal.  I don't know when CASA will move to py3.7, though if I find a timeline I'll try to remember to post it here.
