### ISSUE TITLE
CI failures with dev numpy and astropy

### ISSUE THREAD

**Issue by larrybradley** [astropy/regions#415]
The `TestRectanglePixelRegion::test_as_mpl_selector` test is failing in CI with devdeps (dev numpy and astropy) with a `ZeroDivisionError: float division` (e.g., see https://github.com/astropy/regions/runs/4734505137?check_suite_focus=true#step:6:216). 

I tested this locally with dev astropy and numpy 1.22.0 and the tests pass, so the issue may be with numpy dev.

ping @dhomeier, @astrofrog

**Comment by larrybradley** [comment]
Related to `as_mpl_selector`, `matplotlib 3.5.0` deprecated `rectprops`, which has been renamed `props`.  We could bump the minimum mpl version to 3.5.0 and change the keyword name, or we could add a mpl version check and use `rectprops` for mpl < 3.5.0 and `props` for >= 3.5.0.

Currently these mpl deprecation warning are being filtered:
* https://github.com/astropy/regions/blob/main/regions/shapes/tests/test_ellipse.py#L99
* https://github.com/astropy/regions/blob/main/regions/shapes/tests/test_rectangle.py#L103

**Comment by dhomeier** [comment]
> The `TestRectanglePixelRegion::test_as_mpl_selector` test is failing in CI with devdeps (dev numpy and astropy) with a `ZeroDivisionError: float division` (e.g., see https://github.com/astropy/regions/runs/4734505137?check_suite_focus=true#step:6:216).
> 
> I tested this locally with dev astropy and numpy 1.22.0 and the tests pass, so the issue may be with numpy dev.

Tested on macOS with astropy and numpy dev, I could not reproduce this either. And I am struggling to make sense of the backtrace
```python
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: 'regions._geometry.elliptical_overlap.elliptical_overlap_single_subpixel'
E               
E               Traceback (most recent call last):
E                 File "/home/runner/work/regions/regions/.tox/py39-test-alldeps-devdeps/lib/python3.9/site-packages/regions/shapes/ellipse.py", line 170, in to_mask
E                   fraction = elliptical_overlap_grid(xmin, xmax, ymin, ymax, nx, ny,
E               ZeroDivisionError: float division
```
Naturally, `TestRectanglePixelRegion` is not running any tests on `EllipsePixelRegion`, and `RectanglePixelRegion` is not using `elliptical_overlap_grid` anywhere, so how can this code be reached anywhere in that test?

**Comment by dhomeier** [comment]
> We could bump the minimum mpl version to 3.5.0 and change the keyword name, or we could add a mpl version check and use `rectprops` for mpl < 3.5.0 and `props` for >= 3.5.0.

The current minimum version is 3.1, maybe a bit to big of a jump?
I can actually incorporate the version check relatively easily into #392 (which I had almost forgotten about).

**Comment by larrybradley** [comment]
Yes, I agree.  👍 to adding the version check in #392.

**Comment by larrybradley** [comment]
btw, I can't reproduce this error with dev numpy (1.23.0.dev0+321.g81c5acfed) and astropy (5.1.dev385+g5b6888e17) either.

**Comment by dhomeier** [comment]
Is there a test setup with oldest dependencies (or any matplotlib < 3.5) left now?

**Comment by pllim** [comment]
The CI is using "nightly" numpy (by nightly, they mean weekly), not latest dev. To really try to reproduce this, are you using tox as well? And who knows what Actions is caching around.

If that `ZeroDivisionError: float division` isn't something you worry about, `pytest.mark.filterwarnings(...)` on that one test might do the trick.

**Comment by larrybradley** [comment]
Yes, I'm testing locally with `tox -e test-alldeps-devdeps` locally and everything passes.

**Comment by larrybradley** [comment]
I just switched CI from Azure to Actions, so this test has never passed in Actions.

**Comment by larrybradley** [comment]
The only difference is that Actions is running `tox -e test-alldeps-devdeps` on ubuntu-latest and I'm on macos.

**Comment by dhomeier** [comment]
> If that `ZeroDivisionError: float division` isn't something you worry about, `pytest.mark.filterwarnings(...)` on that one test might do the trick.

But on which one should we put it, if `test_as_mpl_selector` is reported as failing, and the `ZeroDivisionError` is raised on a call that _may_ be run somewhere in `test_ellipse`? Don't think there should be a zero division occurring as well.

**Comment by larrybradley** [comment]
Interesting, the `devdeps` test passes with `macos-latest` (instead of `ubuntu-latest`):
https://github.com/astropy/regions/pull/417

**Comment by larrybradley** [comment]
Also passes with `windows-latest`.  Only `ubuntu-latest` fails. 🤷

**Comment by pllim** [comment]
I wonder if it passes with Ubuntu 18.x 🤪

**Comment by larrybradley** [comment]
Ubuntu 18.04 also fails:  https://github.com/astropy/regions/runs/4742102668?check_suite_focus=true

**Comment by dhomeier** [comment]
Umm, just got the same error from an entirely different test session on macOS 10.14:
```python
python3.9 -m pytest regions/shapes -vk _mpl_selector
===================================================================== test session starts ======================================================================
platform darwin -- Python 3.9.9, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /opt/bin/python3.9
WARNING: AstropyDeprecationWarning: The ignore_warnings class is deprecated and may be removed in a future version.
        Use pytest.mark.filterwarnings instead. [pytest_astropy_header.display]
WARNING: AstropyDeprecationWarning: The catch_warnings class is deprecated and may be removed in a future version.
        Use pytest.warns instead. [astropy.tests.helper]
cachedir: .pytest_cache
PyQt5 5.15.4 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2

Running tests with regions version 0.6.dev77+g4075c70.d20220107.
Running tests in regions/shapes.

Date: 2022-01-07T19:17:11

Platform: macOS-10.14.6-x86_64-i386-64bit

Executable: /opt/bin/python3.9

Full Python Version: 
3.9.9 (main, Dec 29 2021, 01:17:06) 
[Clang 11.0.0 (clang-1100.0.33.17)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.23.0.dev0+369.gf4a3e0787
Scipy: 1.7.3
Matplotlib: 3.6.0.dev1133+g72e95f0467
Cython: 0.29.24
Astropy: 5.1.dev385+g5b6888e17
Shapely: 1.7.1

Using Astropy options: remote_data: none.

Matplotlib: 3.6.0.dev1133+g72e95f0467
Freetype: 2.6.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/Users/derek/git/regions/build/lib.macosx-10.14-x86_64-3.9/.hypothesis/examples')
rootdir: /Users/derek/git/regions, configfile: setup.cfg
plugins: filter-subpackage-0.1.1, arraydiff-0.3, xdist-2.1.0, qt-4.0.2, astropy-header-0.1.2, cov-2.10.1, flaky-3.7.0, remotedata-0.3.2, mock-3.3.1, asdf-2.8.1, forked-1.3.0, openfiles-0.5.0, mpl-0.13, expect-1.1.0, hypothesis-6.14.2, doctestplus-0.10.1, flake8-1.0.6
collected 288 items / 282 deselected / 6 selected                                                                                                              

regions/shapes/tests/test_ellipse.py::TestEllipsePixelRegion::test_as_mpl_selector[False] PASSED                                                         [ 16%]
regions/shapes/tests/test_ellipse.py::TestEllipsePixelRegion::test_as_mpl_selector[True] PASSED                                                          [ 33%]
regions/shapes/tests/test_rectangle.py::TestRectanglePixelRegion::test_as_mpl_selector[False] FAILED                                                     [ 50%]PASSED                                                      [ 66%]
regions/shapes/tests/test_rectangle.py::TestRectanglePixelRegion::test_mpl_selector_drag[False] PASSED                                                   [ 83%]
regions/shapes/tests/test_rectangle.py::TestRectanglePixelRegion::test_mpl_selector_drag[True] PASSED                                                    [100%]

============================================================================ ERRORS ============================================================================
__________________________________________ ERROR at teardown of TestRectanglePixelRegion.test_as_mpl_selector[False] ___________________________________________
TEARDOWN ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
ZeroDivisionError: float division
________________________________________________________________________________
--------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
ZeroDivisionError: float division
________________________________________________________________________________
=========================================================================== FAILURES ===========================================================================
_____________________________________________________ TestRectanglePixelRegion.test_as_mpl_selector[False] _____________________________________________________

cls = <class '_pytest.runner.CallInfo'>, func = <function call_runtest_hook.<locals>.<lambda> at 0x126eeb790>, when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

/opt/lib/python3.9/site-packages/_pytest/runner.py:311: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
/opt/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
/opt/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
/opt/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
/opt/lib/python3.9/site-packages/_pytest/unraisableexception.py:88: in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: 'regions._geometry.elliptical_overlap.elliptical_overlap_single_subpixel'
E               
E               Traceback (most recent call last):
E                 File "/Users/derek/git/regions/build/lib.macosx-10.14-x86_64-3.9/regions/shapes/ellipse.py", line 170, in to_mask
E                   fraction = elliptical_overlap_grid(xmin, xmax, ymin, ymax, nx, ny,
E               ZeroDivisionError: float division

/opt/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
--------------------------------------------------------------------- Captured stderr call ---------------------------------------------------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
ZeroDivisionError: float division
________________________________________________________________________________
=================================================================== short test summary info ====================================================================
FAILED regions/shapes/tests/test_rectangle.py::TestRectanglePixelRegion::test_as_mpl_selector[False] - pytest.PytestUnraisableExceptionWarning: Exception ign...
ERROR regions/shapes/tests/test_rectangle.py::TestRectanglePixelRegion::test_as_mpl_selector[False]
===================================================== 1 failed, 5 passed, 282 deselected, 1 error in 2.20s =====================================================
```
– again no obvious connection to `ellipse.py`, but I am wondering about the
`TEARDOWN ERROR: Exceptions caught in Qt event loop:`
as if there is something – perhaps from the `MouseEvent` operations – not properly cleaned up.
To add a bit more to the confusion:

1. This was a singular failure I've not been able to repeat with `pytest -k _mpl_selector` so far.
2. It does come up entirely consistently when running `pytest -k ePixelRegion`.
3. I no longer see it when removing or skipping either one of the two `test_as_mpl_selector` (`test_mpl_selector_drag`, which is a newly added test using almost the same `MouseEvent` ops, seems to have no impact on this).

**Comment by larrybradley** [comment]
I also noticed that the test fails only with `sync=False`, which uses a dummy callback function.

**Comment by dhomeier** [comment]
But that's used in many of the matplotlib selector tests as well, afaict.

New data point:
Locally everything runs without the error after replacing all the manual `MouseEvent` movements with convenience functions from `matplotlib.testing.widgets`. They would also clean up the code quite a bit, so maybe worth a try.
They were only introduced in 3.3 though, so this would either require pushing the minver after all, or just skipping the test for 3.3-3.4.x (the interesting applications will require 3.5/3.6 anyway).

**Comment by larrybradley** [comment]
Another data point:

I simply removed the `test_ellipse.py` module and the tests pass on ubuntu (https://github.com/astropy/regions/runs/4743133520?check_suite_focus=true).  So, something is leaking from the ellipse `as_mpl_selector` test to the rectangle `as_mpl_selector` test (which explains why the traceback references the ellipse function).

**Comment by dhomeier** [comment]
Yes; same when I deselected the ellipse test.
But using `on_select` they are passing now as well. Personally that would be my preferred solution, just need to decide what to do about the older matplotlib versions.

**Comment by larrybradley** [comment]
Perhaps we should leave the matplotlib min version for the package at 3.1+, but require 3.3+ (or whatever version is appropriate) for the selectors?  i.e. raise a warning that that the selectors require mpl 3.3+?  Just a thought.

**Comment by larrybradley** [comment]
On second thought, mpl 3.1 came out in May 2019, 3.3 in July 2020.  So, I'm fine with bumping the minimum mpl version to 3.3.

**Comment by larrybradley** [comment]
astropy is using `matplotlib>=3.1,!=3.4.0`, but maybe that should be updated.

**Comment by dhomeier** [comment]
The selectors themselves are not the problem, I think, just testing them.
The old tests are still passing with 3.1.0, with the notable exception of `drag_from_anywhere`, which was only introduced in 3.5 as well – so if I am going to mention it in the docstring, I better point out the minver.
