### ISSUE TITLE
Adapt travis-ci build matrix

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#43]
The travis-ci builds for this repo are currently broken since I merged #42 yesterday:
https://travis-ci.org/astropy/regions?branch=master

The reason is that we have Astropy 1.0 LTS tests in the build matrix.
Those builds should be removed.
The plan with this code is that it's added to astropy master and becomes part of Astropy core 1.3.
So IMO there's no point in testing and supporting old Astropy versions.

@bsipocz - Do you have time to adapt the build matrix or should I?
(What's the best way ... delete lines or comment them out in `.travis.yml`?)

**Comment by bsipocz** [comment]
> @bsipocz - Do you have time to adapt the build matrix or should I?
> (What's the best way ... delete lines or comment them out in .travis.yml?)

Either way is fine, today I plan to catch up with admin and these kind of trivial fixes, so can put it on the list, too.
