### ISSUE TITLE
Ellipse aperture sum inconsistent with photutils

### ISSUE THREAD

**Issue by pllim** [astropy/regions#442]
I found this while working on spacetelescope/jdaviz#1138 and thought I would report it here. Both apertures from regions and photutils used "exact" but resulted in different coverage. As a result, the aperture sum jumped from 7.07 to 28.3 when I switched from regions to photutils.

| Imviz Subset | regions | photutils |
| --- | --- | --- |
| ![Screenshot 2022-03-09 124011](https://user-images.githubusercontent.com/2090236/157508053-4769a119-a1eb-4a8b-81dc-9bd1f5ae16de.png) | ![Screenshot 2022-03-09 124012](https://user-images.githubusercontent.com/2090236/157508054-7491effc-d7af-4e6f-95bd-6aa49cd9ac4c.png) | ![Screenshot 2022-03-09 124013](https://user-images.githubusercontent.com/2090236/157508055-c5254b2b-b8a2-4cb9-b727-84f43f221c5f.png) |

```python
>>> import numpy as np
>>> from photutils.aperture import EllipticalAperture, aperture_photometry
>>> from regions import EllipsePixelRegion, PixCoord
>>> reg = EllipsePixelRegion(center=PixCoord(x=4.5, y=2.0), width=4.5, height=2.0)
>>> reg
EllipsePixelRegion(center=PixCoord(x=4.5, y=2.0), width=4.5, height=2.0, angle=0.0 deg)
>>> aper = EllipticalAperture((4.5, 2), a=4.5, b=2)
>>> aper
<EllipticalAperture([4.5, 2. ], a=4.5, b=2.0, theta=0.0)>
>>> comp_no_bg = np.ones((10, 10))
>>> old_aper_mask = reg.to_mask(mode='exact')
>>> old_img = old_aper_mask.get_values(comp_no_bg, mask=None)
>>> old_rawsum = np.nansum(old_img)
>>> old_rawsum  # regions
7.068583470577034
>>> phot_table = aperture_photometry(comp_no_bg, aper)
>>> phot_table['aperture_sum']  # photutils
28.27433388230814
```

**Comment by larrybradley** [comment]
You aren't defining the same region.  In `photutils`, ellipses are defined using the *semi*major (`a`) and *semi*minor axes (`b`).  In `regions`, ellipses are defined using `width` and `height`, which are the *full* width and height.  For example, `a = 4.5` in `photutils` corresponds to a full width of `width = 9.0`.

**Comment by pllim** [comment]
In Imviz, the `reg` I get is actually from [glue-astronomy translator](https://github.com/glue-viz/glue-astronomy/blob/347cb4196c50640fe4b41cac8a918cc75b64366c/glue_astronomy/translators/regions.py#L85). The green line is the true shape I drew in the app. So, do you think the regions shape or the photutils aperture is more correct?

**Comment by larrybradley** [comment]
The green line appears to correspond to the `photutils` aperture.

**Comment by larrybradley** [comment]
Perhaps there is a bug in the glue to `regions` translator.

**Comment by pllim** [comment]
Well, this is funny then... the bug in glue-astronomy translator + the bug in my own translation = correct result.

**Comment by larrybradley** [comment]
Two bugs make it right. 😄

**Comment by pllim** [comment]
`#laughcry`

**Comment by pllim** [comment]
I'll close this after I figure out how to follow-up on this revelation properly. 🤪
