### ISSUE TITLE
Is there a way to "invert" a region's mask?

### ISSUE THREAD

**Issue by janerigby** [astropy/regions#452]
I'm looking for a way to use Astropy regions to select all pixels that are *not* in a given region.  For example, I want to define a region to contain a bright star, and then compute the median of all pixels that are not within the region.    I feel like this should be easy with a to_mask() and mask.multiply(), but for the life of me I can't figure it out.  Here's what I'm trying to do, with psuedocode at the middle step:

```
mask = CircularAperture.to_mask()
the_rest = mask.some_method_that_inverts_selection_and_cuts_it_out(data)
np.median(the_rest)
```
Any suggestions?

**Comment by keflavich** [comment]
I think you want:
```python
np.median(data[~mask.to_image(data.shape)])
```

**Comment by larrybradley** [comment]
@janerigby You have `CircularAperture` in your example, so I'm assuming you meant `photutils` instead of `regions`.

The `photutils` aperture `to_mask` default method is "exact", which will return a mask with fractional pixel weights.  To use that to compute a median, you would need to use a weighted-median function, which doesn't exist in numpy or astropy.

Instead, you can use the "center" method to return a mask where the weights are all 0 or 1 (full pixels), then invert that and covert to a boolean mask:

```python
import numpy as np
from photutils import CircularAperture

rng = np.random.default_rng(seed=123)
data = rng.random((101, 101))
aper = CircularAperture((50, 50), r=10)

mask = aper.to_mask(method='center')
aper_weights = mask.to_image(data.shape)
inv_mask = (1. - aper_weights).astype(bool)  # inverse bool mask
np.median(data[inv_mask])
```

**Comment by janerigby** [comment]
Thank you @keflavich !  When I try that, I get this error:

TypeError                                 Traceback (most recent call last)
/var/folders/cx/gfw9hxb91ld7bpd_wcpl6gjhmz2qhx/T/ipykernel_4301/3498381707.py in <module>
----> 1 np.median(data[~mask.to_image(data.shape)])

TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by keflavich** [comment]
🤔 well, not sure what that means exactly.  Try Larry's approach, which is basically the same but more clearly spelled out and broken onto different lines, which will make it debuggable

**Comment by larrybradley** [comment]
@janerigby That error is because `mask.to_image(data.shape)` returns an array of float type (not boolean type).  The`~` (the python binary NOT operator) fails for float.  Try my example.
