### ISSUE TITLE
Regions reports a region overlaps an image when it does not

### ISSUE THREAD

**Issue by janerigby** [astropy/regions#453]
I'm trying to do a simple test of whether a sky region is contained within an image.  I'm following the documentation in https://astropy-regions.readthedocs.io/en/stable/masks.html  , but that proceedure reports overlap (non-zero elements in pixreg.to_mask().data) when there is no overlap.  Here's what's happening.

Converting the region from sky coordinates to pixel coordinates:
`pixreg = thisreg.to_pixel(thewcs)`
returns this pixreg:
`<CirclePixelRegion(center=PixCoord(x=3049.8207282558615, y=2112.0466553641672), radius=18.047624476048696)>`
Which is way outside the bounds of the image.

I know that, but I want the tool to tell me that there's no overlap, so I can skip that region.  But that's not what the tool is doing.  If we just plow forward and check the overlap:
`pixreg.to_mask().data  `
Then the result is a 37x37 pixel array, in which 1023 out of 1369 pixels have a value of 1, and the rest are zero.

I can send the image and the region file by email if that would help.

**Comment by larrybradley** [comment]
`pixreg.to_mask().data` gives you the fractional pixel weights for the aperture.  The region mask is self contained knows nothing about your image -- it only defines its weights and bounding box.  It's defined this way for maximum reusability (it can apply to any image).

If you want to know if the region mask overlaps your image, you will need to tell it about your image.  There are a couple of ways to do this.  Here are some examples:

```python
>>> from regions.core import PixCoord
>>> from regions.shapes.circle import CirclePixelRegion

# region and region mask do not know anything about any images
>>> region = CirclePixelRegion(PixCoord(5000, 5000), 10)
>>> mask = region.to_mask()

# now define a small image that the region does not overlap
>>> data = np.ones((51, 51))

# here are a few ways to check for overlap of the region mask with the data
>>> mask.get_values(data)
array([], dtype=float64)  # empty array

>>> mask.get_overlap_slices(data.shape)
(None, None)   # returns tuple of 'None's

>>> result = mask.multiply(data)
>>> result is None  # returns None
True
```

```

**Comment by larrybradley** [comment]
@janerigby I'm going to close these older issues.  Please reopen if you have more questions.
