### ISSUE TITLE
Use Pix or Pixel consistently

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#47]
Currently we have a class [PixCoord](http://astropy-regions.readthedocs.io/en/latest/api/regions.PixCoord.html), and everywhere else the longer form "Pixel" is used, e.g. in [PixelRegion](http://astropy-regions.readthedocs.io/en/latest/api/regions.PixelRegion.html).

See http://astropy-regions.readthedocs.io/en/latest/api.html

We should make it consistent now and the question is which way to go?

- "Pix" - short and sweet, same length as the corresponding "Sky", used in many parts of the API in Astropy already (see [here](http://astropy.readthedocs.io/en/latest/search.html?q=pix&check_keywords=yes&area=default)).
- "Pixel" - more explicit, used in many parts of the API in Astropy already (see [here](http://astropy.readthedocs.io/en/latest/search.html?q=pixel)).

@keflavich @astrofrog @eteq @larrybradley @joleroi - Please leave a comment mentioning your preference.

**Comment by keflavich** [comment]
`Pixel`.  :+1: this if you vote this way; if anyone posts the contrary opinion, 👍  that

**Comment by joleroi** [comment]
``Pix``

**Comment by astrofrog** [comment]
Ahhh, I can't decide!

**Comment by joleroi** [comment]
![64316814](https://cloud.githubusercontent.com/assets/11678435/16378535/b918ca78-3c6c-11e6-92cc-922023ecc80a.jpg)

**Comment by bsipocz** [comment]
@joleroi - you should ``import this`` :)

**Comment by joleroi** [comment]
> Beautiful is better than ugly.   :wink:

**Comment by bsipocz** [comment]
Come on, you're German, so must love long words ;)

**Comment by larrybradley** [comment]
Tough one, but my first instinct was `Pixel`.

**Comment by astrofrog** [comment]
The thing is that for ``PixCoord`` it makes more sense to use ``Pix`` since then both are abbreviated, but for ``PixelRegion`` the full word makes more sense. Is the status quo not an option? :)

**Comment by joleroi** [comment]
What about ``SkyReg`` and ``PixReg`` :smiling_imp: ?

**Comment by cdeil** [comment]
To summarise: @keflavich, @bsipocz and @larrybradley like "PixelCoord", @joleroi likes "PixCoord", but no-one felt strongly about it. Except maybe @joleroi :-)

> The thing is that for PixCoord it makes more sense to use Pix since then both are abbreviated, but for PixelRegion the full word makes more sense. Is the status quo not an option? :)

Yes, it is an option.
I didn't think of this argument when filing the issue.
I do like how "PixCoord" is short and both "Pix" and "Coord" are abbreviated and it's symmetric to "SkyCoord".

Should we go with that option ... leave all names as-is?

**Comment by keflavich** [comment]
hmm... `explicit > implicit`, `beautiful > ugly`.... but also `good > perfect` and `no work > work`.  Therefore, sure, status quo.

**Comment by larrybradley** [comment]
I'm fine with the status quo.

**Comment by bsipocz** [comment]
I'm very happy with the logic that @astrofrog found in the current naming, so 👍 to status quo.

**Comment by cdeil** [comment]
OK, let's leave as-is.

Sorry for the noise!

At least we'll have this issue to refer people to should the question come up again when the time for the PR for `astropy.regions` against the core repo comes. :-)
