### ISSUE TITLE
Frame flag causing DS9 issues 

### ISSUE THREAD

**Issue by robelgeda** [astropy/regions#472]
I was trying to load a region file with multiple pixel regions into ds9 and noticed that ds9 fails to show them. When I remove the `image` frame flag, the regions load without issue:

`astropy/regions` output:
```
# Region file format: DS9 astropy/regions
image
ellipse(4270.66666667,3920.11111111,4.72177800,3.31567550,91.35243988)
ellipse(4257.26315789,4001.36842105,3.59479710,2.64991160,74.76722717)
ellipse(4147.92857143,4015.30000000,7.71550200,4.73446040,65.32648468)
ellipse(4189.58974359,4017.76923077,3.76458240,3.29147930,123.85412598)
```

Hack to get ds9 to work
```
# Region file format: DS9 astropy/regions

ellipse(4270.66666667,3920.11111111,4.72177800,3.31567550,91.35243988)
ellipse(4257.26315789,4001.36842105,3.59479710,2.64991160,74.76722717)
ellipse(4147.92857143,4015.30000000,7.71550200,4.73446040,65.32648468)
ellipse(4189.58974359,4017.76923077,3.76458240,3.29147930,123.85412598)
```

The issue with the hack is that we cant load it back into `astropy/regions`.

Regions v0.6, DS9 v8.1

**Comment by keflavich** [comment]
Could you report this to the ds9 devs too?  I think the latter is actually wrong?  But if we've misread the specification (...really there isn't one...) it would be good to know.

**Comment by larrybradley** [comment]
@keflavich  If no frame is specified, then DS9 defaults to the `physical` frame.  Regions does not support the `physical` frame because it relies on  using LTM/LTV header keywords.

@robelgeda Your region file looks perfectly ok to me.  The pixel coordinates for the ellipse centers are large ~(4200, 4000).  Is you image larger than this such that the ellipses can be displayed?

**Comment by larrybradley** [comment]
@robelgeda I just tested your region file (with a large image) and the region file loaded fine and displayed the regions.  The regions are quite small (for a large image) so I needed to zoom in to see them clearly.

<img width="738" alt="Screen Shot 2022-07-21 at 2 12 24 PM" src="https://user-images.githubusercontent.com/4992897/180284445-3aa512c4-8d18-4673-bc4f-4c04944a93d3.png">

**Comment by robelgeda** [comment]
Hi @larrybradley ! I am looking at x-ray event files form Chandra. Which DS9 are you using. If it is the same as mine, I could try to post the fits and regions file

**Comment by larrybradley** [comment]
8.4b1

**Comment by larrybradley** [comment]
It also works fine for me in 8.3.

If you are on a mac and have `homebrew`, you can install ds9 using:

`brew install larrybradley/astro/ds9`

**Comment by larrybradley** [comment]
If you are still having issues, please send me the image and region file so I can test it.

**Comment by robelgeda** [comment]
Still having issues, I uploaded it google drive:

[event data](https://drive.google.com/file/d/1URjKCOgUcPK2ysdlznwwjXbmyRd_1LN3/view?usp=sharing)
[regions](https://drive.google.com/file/d/16efAtd7Wdc7sbzi9r3ni6sZZomxuiqa5/view?usp=sharing)

**Comment by larrybradley** [comment]
@robelgeda Your image only has ~1024 x 1024 pixels .  However, the regions you are plotting are centered at ~(4200, 4000), which is way outside of the image region.  If you zoom out in DS9, you'll see that the regions have been correctly loaded and displayed, but they are outside of image pixels (see attached image).


![regions](https://user-images.githubusercontent.com/4992897/180318237-2a0749e2-7aff-432a-a2ef-638cc0f59513.jpg)

**Comment by robelgeda** [comment]
Ah I figured it out, I am using `physical` frame instead of image frame! Thank you @larrybradley for taking the time. I will close this issue now.
