### ISSUE TITLE
Is this package compatible with Python 3.11 ?

### ISSUE THREAD

**Issue by pllim** [astropy/regions#475]
When trying to run CI for Jdaviz using Python 3.11, we encountered this error:

```
ERROR: Could not build wheels for h5py, regions, which is required to install pyproject.toml-based projects
```

xref https://github.com/spacetelescope/jdaviz/pull/1654

**Comment by larrybradley** [comment]
Fixed in https://github.com/astropy/regions/pull/476

**Comment by pllim** [comment]
I am not sure if #476 completely fix this issue. You probably want to also add Python 3.11 to https://github.com/astropy/regions/blob/main/.github/workflows/ci_tests.yml just to be sure.

**Comment by larrybradley** [comment]
Thanks.  Let's see:  https://github.com/astropy/regions/pull/477
