### ISSUE TITLE
pix_reg.to_sky fails even with only 2 wcs axes

### ISSUE THREAD

**Issue by wjcramer** [astropy/regions#478]
Hi,

I'm having an issue with the code trying to convert regions from pixel to wcs coordinates.

`filename = 'NGC_XYZ.mom0.fits'
hdulist = fits.open(filename)
w = wcs.WCS(hdulist[0].header, hdulist, naxis=2)
hdulist.close()

print(w)`

Results in:

WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 36.44271375820084  -3.925248141001513  
CRPIX : 1499.637752946587  1497.87391274248  
CD1_1 CD1_2  : -1.8055555555555e-05  7.70613464114037e-23  
CD2_1 CD2_2  : 7.88396389795642e-23  1.80555555555555e-05  
NAXIS : 3001  2993

However, when I then try 

`sky_reg = pix_reg.to_sky(wcs)`

I get an error message

AttributeError                            Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 sky_reg = pix_reg.to_sky(wcs)

File /opt/anaconda3/lib/python3.9/site-packages/regions/shapes/rectangle.py:109, in RectanglePixelRegion.to_sky(self, wcs)
    108 def to_sky(self, wcs):
--> 109     center = pixel_to_skycoord(self.center.x, self.center.y, wcs)
    110     _, pixscale, north_angle = pixel_scale_angle_at_skycoord(center, wcs)
    111     width = Angle(self.width * u.pix * pixscale, 'arcsec')

File /opt/anaconda3/lib/python3.9/site-packages/astropy/wcs/utils.py:612, in pixel_to_skycoord(xp, yp, wcs, origin, mode, cls)
    609 if cls is None:
    610     cls = SkyCoord
--> 612 if _has_distortion(wcs) and wcs.naxis != 2:
    613     raise ValueError("Can only handle WCS with distortions for 2-dimensional WCS")
    615 # Keep only the celestial part of the axes, also re-orders lon/lat

File /opt/anaconda3/lib/python3.9/site-packages/astropy/wcs/utils.py:497, in _has_distortion(wcs)
    493 def _has_distortion(wcs):
    494     """
    495     `True` if contains any SIP or image distortion components.
    496     """
--> 497     return any(getattr(wcs, dist_attr) is not None
    498                for dist_attr in ['cpdis1', 'cpdis2', 'det2im1', 'det2im2', 'sip'])

File /opt/anaconda3/lib/python3.9/site-packages/astropy/wcs/utils.py:497, in <genexpr>(.0)
    493 def _has_distortion(wcs):
    494     """
    495     `True` if contains any SIP or image distortion components.
    496     """
--> 497     return any(getattr(wcs, dist_attr) is not None
    498                for dist_attr in ['cpdis1', 'cpdis2', 'det2im1', 'det2im2', 'sip'])

AttributeError: module 'astropy.wcs' has no attribute 'cpdis1'

It seems to suggest if the number of wcs axes is not 2, it needs these distortion keywords. But as I showed in the first code snippet, the number of wcs axes is equal to 2, so I'm not sure what the issue is here. I've tried this with multiple types of fits images as input and get the same error every time.

Thanks!

**Comment by keflavich** [comment]
I've seen this error with non-FITS-WCS objects, but not with FITS WCS, and you're working with a FITS WCS object, so that aspect is new to me.

The issue is not the number of axes, though, but the absence of the `cpdis1` attribute, which suggests that an incompatible class is being used.

**Comment by wjcramer** [comment]
Hmm, I tried with both a pipeline reduced basic HST image, as well as ALMA, and Subaru fits iamges. All got the same message. Furthermore, if I'm interpreting this correctly it seems the error should only be thrown:

if _has_distortion(wcs) and wcs.naxis != 2:

And in this case, as far as I can tell, wcs.naxis = 2

**Comment by keflavich** [comment]
Yes, exactly: that failure is happening because `_has_distortion(wcs)` is producing a traceback, not because of anything to do with `wcs.naxis`.

I'm not clear why the `cpdis1` attribute is missing.

**Comment by larrybradley** [comment]
@wjcramer Why did you set `naxis=2` when creating a `WCS` object?  Are you trying to take a 2D subset from a 3D WCS?  If so, you can try not adding `naxis=2` and then to get the 2D celestial part of the WCS, do `wcs.celestial`.

**Comment by larrybradley** [comment]
Essentially, if `wcs.pixel_to_world(x, y)` fails for your `wcs` object with some (x, y) image coordinate, then this is an issue with your WCS object.

**Comment by larrybradley** [comment]
Please reopen if this didn't solve your issue.
