### ISSUE TITLE
PyPI releases!

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#48]
At `PyAstro16` we discussed that this `astropy/regions` package should be developed quickly in this repo at https://github.com/astropy/regions/ and then be merged in the Astropy core repo.

There hasn't been much development on `astropy/regions` after `PyAstro16` though, there isn't much functionality, tests, docs yet ... it's not clear if it's feasible to get this done and stable before for Astropy 1.3.

I'd like to propose that we start doing releases on PyPI and announce them on `astropy-dev`, starting with 0.1 very soon (in a week or two).

A personal motivation for that is that I don't like having to update the bundled version of this package at [gammapy.extern.regions](https://github.com/gammapy/gammapy/tree/master/gammapy/extern/regions) because we have started using it for circles and need it to be available to end users. The main reason is that I think releases on PyPI and announcements on astropy-dev might attract some co-developers to this package and having had users means that the API and implementation is likely more robust when the time comes to move this to Astropy core.

I'd be happy to make the releases, and if someone else (@joleroi, @keflavich) wants to, even better!

Concerning package name, I propose plain `regions` (which amazing wasn't taken, so I reserved it right now: https://pypi.python.org/pypi/regions ) This is nice because it's the same as the current repo and package name, i.e. no confusion by users or developers.

I did consider `astropy-regions` as package name. That's more explicit, but also longer and then some people get confused if PyPI package and installed package names are different.

@keflavich @astrofrog @joleroi @eteq @larrybradley - Thoughts?

**Comment by keflavich** [comment]
I agree that we need a spur for further development.  pypi release is a good move in that direction, so I support it.

**Comment by cdeil** [comment]
https://github.com/astropy/regions/milestones/0.1

**Comment by cdeil** [comment]
I'll make the 0.1 release this Saturday, July 9.

@astropy/regions-developers - If you have time to implement or improve something in `astropy/regions` in the next two days, please open up an issue or PR and put it under the 0.1 milestone.

**Comment by astrofrog** [comment]
+1 to making releases, it would be good to get usage before we consider merging into astropy anyway. I've gone down that route for wcsaxes and reproject.

**Comment by astrofrog** [comment]
Note that I think we should get https://github.com/astropy/regions/pull/20 merged in before the 0.1 release - but I don't have time to investigate the failures (there aren't many) - could someone else take a look at this?

**Comment by cdeil** [comment]
I just merged #50 , we now have some docs:
* http://astropy-regions.readthedocs.io/en/latest/
* http://astropy-regions.readthedocs.io/en/latest/getting_started.html

I'll try to find time to work on this some more in the coming days.
Help would be appreciated, especially with #41  and writing this part: http://astropy-regions.readthedocs.io/en/latest/getting_started.html#ds9-region-strings and

**Comment by cdeil** [comment]
FYI: I plan to make the 0.1 release later today after merging #60.

I know there's a lot of things to be improved, but why not "release early and often"!?

**Comment by cdeil** [comment]
I've made the v0.1 tag and uploaded the sdist to PyPI:
https://pypi.python.org/pypi/regions

@astropy/regions-developers - Please test if `pip install regions` and `python -c 'import regions; regions.test()' works for you.

@bsipocz @mwcraig - Can you please make a conda package for `regions`?

@joleroi or @keflavich - Looks like I don't have permission at http://readthedocs.org/projects/astropy-regions/ to see the project settings and add "v0.2" as one that should be built. Whoever has permissions for this repo on RTD: please add me.

**Comment by bsipocz** [comment]
> @bsipocz @mwcraig - Can you please make a conda package for regions?

Sure, I'm on it.

**Comment by cdeil** [comment]
@keflavich, @larrybradley , @astrofrog - FYI: I've added you as owners on PyPI for
https://pypi.python.org/pypi/regions
just in case I get 👊  by a 🚌 .

**Comment by cdeil** [comment]
Is there a template or good example for package release announcements?
Or should I just write something?
(in any case, I'll wait a few days in case there's an issue and so that the conda package is ready)

**Comment by larrybradley** [comment]
@cdeil  `pip install regions` works for me and all tests pass.  Thanks!

**Comment by bsipocz** [comment]
Tests pass for me, too.

**Comment by bsipocz** [comment]
Conda package: https://github.com/astropy/conda-channel-astropy/pull/59

**Comment by cdeil** [comment]
@bsipocz - Thanks!

Could you please make a PR updating the install instructions in master concerning conda install?
http://astropy-regions.readthedocs.io/en/latest/installation.html

I think all that's needed is the command to run, and link to the URL where info about this conda package will be.

Is it this?
```
conda install --channel astropy regions
```
https://anaconda.org/astropy/regions

**Comment by bsipocz** [comment]
Sure. I got to go know, but will be back later this evening.

**Comment by cdeil** [comment]
@bsipocz and @mwcraig - Thanks for making the conda package.
For me this works on Mac with Python 3.4:
```
conda install -c astropy regions
python -c 'import regions; regions.test()'
```
Maybe others here can try as well.

@joleroi - Looks like you're owner on RTD: http://readthedocs.org/projects/astropy-regions/
Can you make me (and maybe @keflavich @larrybradley @astrofrog ) co-owner so that we have permission to do such things as adding "v0.1" on RTD?

**Comment by joleroi** [comment]
@cdeil I added you as maintainer on RTD, if others tell me (or you) their RTD names I (or you) can add them.

**Comment by larrybradley** [comment]
I'm **bradley** on RTD.

**Comment by joleroi** [comment]
I get this when trying to install the package

```
[/home/kingj] conda install -c astropy regions
Fetching package metadata: ............
Solving package specifications: ..............
Error: Could not find some dependencies for regions: pytest-mpl
```

**Comment by cdeil** [comment]
`pytest-mpl` shouldn't be a required dependency for `regions`.

I downloaded https://anaconda.org/astropy/regions/0.1/download/linux-64/regions-0.1-py35_0.tar.bz2
and looked at `info/recipe/meta.yaml` (a copy is here:
https://gist.github.com/cdeil/6c3a3c9172370fa17d51f5d71bc5f3e2#file-meta-yaml-L37
https://anaconda.org/astropy/regions)
```
  run:
  - python
  - astropy
  - pytest-mpl
  - matplotlib
  - wcsaxes
```
The `pytest-mpl`, `matplotlib` and `wcsaxes` dependencies are optional, they should never prevent conda install of regions.

@bsipocz and @mwcraig -- Can you change this?

I guess either we remove `pytest-mpl`, `matplotlib` and `wcsaxes` from the dependency list, and tell users to get the "full-featured version" by separately conda installing this in the docs.

Or we have two conda packages, e.g. `regions` and `regions-all`, or `regions-core` and `regions`.

We had the same issue / discussion for Gammapy, I think there also a proper solution isn't implemented yet for the conda builds.

**Comment by cdeil** [comment]
@joleroi - Thanks for giving me access to RTD.

We now have this:
- http://astropy-regions.readthedocs.io/en/v0.1/
- http://astropy-regions.readthedocs.io/en/stable/
- http://astropy-regions.readthedocs.io/en/latest/
where stable currently points to v0.1

So all that's left to do is fix the conda package issue before sending out the release announcement.

**Comment by bsipocz** [comment]
@mwcraig - It seems that the ``extras_require`` packages are picked up into the automatic recipe. Should we create one manually and edit these out from it, or you have a better solution in mind?

**Comment by mwcraig** [comment]
@bsipocz that option got added at `pyastro16` when I sunpy needed (or at least wanted) extras, with the thought "Why not? What could go wrong?".

You can add this to requirements to prevent it: `include_extras: false`

**Comment by bsipocz** [comment]
>  "Why not? What could go wrong?".

Usually the answer to this is that everything will go wrong, especially where you're not expecting it. At least this is the way things work/stop working in ci-helpers ;)

**Comment by cdeil** [comment]
@bsipocz @mwcraig - Thanks!

I've had issues and head scratching because of stealth updates over the years, so 👍  to implement the build number update feature.
But sure, agreed, it's OK to do a stealth update in this case, almost no-one will be affected.

**Comment by bsipocz** [comment]
I'm inclined to do the update now, rather than wait until the build number bumping is implemented. This is rather a trivial change that only fixes bugs (see, this is the other problematic statement that is hardly ever true).

The only other affected package is astroplan, but the conda packages for it was build before pyastro16, so it looks fine.

**Comment by bsipocz** [comment]
@cdeil - The conda packages should show up in the next ~30 mins here https://anaconda.org/astropy/regions/files

**Comment by cdeil** [comment]
@bsipocz - Thanks!

The `meta.yaml` now correctly only has Astropy as dependency:
```
  run:
  - python
  - astropy
```

@joleroi - You could try conda install again:
http://astropy-regions.readthedocs.io/en/latest/installation.html#using-conda

I'll try to find time to wrap this up and send an announcement to astropy-dev tomorrow, if not on Monday.

**Comment by cdeil** [comment]
I've sent the release announcement to astropy-dev:
https://groups.google.com/forum/#!topic/astropy-dev/QjXUl6wgM6M

I'm closing this issue now.
We can use #63 to discuss the next release: version 0.2.
