### ISSUE TITLE
FEAT: missing RectangleSkyRegion.to_mask method ?

### ISSUE THREAD

**Issue by neutrinoceros** [astropy/regions#490]
I'm trying to migrate the following code from `pyregion` to `regions`
```python
import pyregion
from astropy.io.fits.header import Header

header = Header(
    dict(
        WCSAXES=2,
        CRPIX1=8293.027842001,
        CRPIX2=179.000003796,
        CDELT1=-0.006150000045741,
        CDELT2=0.006150000045741,
        CUNIT1="deg",
        CUNIT2="deg",
        CTYPE1="GLON-CAR",
        CTYPE2="GLAT-CAR",
        CRVAL1=0.0,
        CRVAL2=0.0,
        LONPOLE=0.0,
        LATPOLE=90.0,
        MJDREF=0.0,
        NAXIS1=325,
        NAXIS2=357,
    )
)

reg = pyregion.parse('galactic;box(+49:26:35.150,-0:30:04.410,1926.1927",1483.3701",0.0)')

header["NAXIS1"] = nx = ds.domain_dimensions[ds.lon_axis]
header["NAXIS2"] = ny = ds.domain_dimensions[ds.lat_axis]
filter = r.get_filter(header=header)
mask = filter.mask((ny, nx)).transpose()
```

(this code is a simplified version from `yt.frontends.fits.misc.ds9_regions()`)

from #488, I got that the region can be parsed as
```python
from regions import Regions
reg = Regions.parse('galactic;box(+49:26:35.150,-0:30:04.410,1926.1927",1483.3701",0.0)').regions[0]
# reg is now a RectangleSkyRegion object
```
but it's not quite clear how to obtain the `mask` after that. From the docs I see that some region classes have a `to_mask` method which looks very appropriate here, but unfortunately it doesn't seem to be implemented in the one class that yt actually uses as an example, namely `RectangleSkyRegion`.

Would it make sense to implement it ?

**Comment by neutrinoceros** [comment]
Thank you !
If I understand correctly this is how I can reproduce the old behaviour (retrieving a numpy mask array)

```python
pixreg = r.to_pixel(WCS(header))
mask = pixreg.to_mask().data.astype(bool)
```

however there seems to be a bug sill, in that the mask array doesn't have the expected shape
```
>>> print(WCS(header).pixel_shape)
(325, 357)
>>> print(mask.shape)
(68, 88)
```

Is this a bug or am I doing something wrong ?

**Comment by larrybradley** [comment]
```python
mask = pixreg.to_mask().data.astype(bool)
```
gives you the mask for the region within its bounding box.  It is not tied to any particular data set or image size.  If you want to apply the mask to a particular image size, then you need to use the `to_image` method with a specified shape:

```python
mask = pixreg.to_mask().to_image(shape).astype(bool)
```

**Comment by neutrinoceros** [comment]
It seems that I have everything I needed to migrate yt, so I'll close this. Thanks @keflavich and @larrybradley for your help, much appreciated !
For reference,!the migration in question is at https://github.com/yt-project/yt/pull/4235
