### ISSUE TITLE
How to convert a list of ra and dec into a ds9 region file?

### ISSUE THREAD

**Issue by mayukh4** [astropy/regions#493]
I have a numpy array of ra and dec coordinates which I first make a skycoord object and then try to write a region file from that.
![image](https://user-images.githubusercontent.com/25118297/206763659-25045560-9a1f-4cd4-8399-3b787743bf68.png)

I keep getting this error :
'center' must be a scalar SkyCoord

Amy suggestions?

**Comment by mayukh4** [comment]
> The center `SkyCoord` input to `CircleSkyRegion` must be _scalar_, i.e., only have one RA/Dec coordinate. (use `center.isscalar` to check).
> 
> You need to create a `CircleSkyRegion` for each coordinate and then pass a list of `CircleSkyRegion` objects to the `Regions` class, which can then written to a DS9 file.

Hey Larry, 

Thanks for getting back, I actually tried something like that, but I guess the "Regions" class cannot recognize a list. 
![image](https://user-images.githubusercontent.com/25118297/206765828-9c3b8784-0a83-4001-a1c3-0663388f31f2.png)

Maybe I am doing something wrong?

**Comment by larrybradley** [comment]
You're close, but missing a step.  `reglist` is just a regular python list.  You need to create a `Regions` object (https://astropy-regions.readthedocs.io/en/stable/api/regions.Regions.html#regions.Regions) from your `reglist`:
```python
>>> from regions import Regions
>>> regs = Regions(reglist)
>>> reg.write(....)
```

**Comment by mayukh4** [comment]
> ```python
> from regions import Regions
> ```

Perfect! This makes sense. Thanks so much for getting back quickly 👍
