### ISSUE TITLE
WCS coordinate conversion crashes with new numpy versions

### ISSUE THREAD

**Issue by jusneuma** [astropy/regions#504]
```
File "~/pyregion/wcs_converter.py", line 92, in <genexpr>
    np.asscalar(x)
  File "~/numpy/__init__.py", line 311, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'asscalar'. Did you mean: 'isscalar'?
```

asscalar has been removed from numpy at least since v. 1.23

proposed solution `np.asscalar` => `np.ndarray.item`

**Comment by keflavich** [comment]
You're posting this issue on the wrong repository; `regions` hasn't used `asscalar` since 2019: https://github.com/astropy/regions/pull/252.  Your issue might be relevant on https://github.com/astropy/pyregion

**Comment by jusneuma** [comment]
Oh, so sorry I got the repository wrong. Thanks !
