### ISSUE TITLE
BUG: stable docs has incorrect version number

### ISSUE THREAD

**Issue by bsipocz** [astropy/regions#536]
Same issue as https://github.com/astropy/specutils/issues/1092, I suspect there is a shallow clone somewhere that trips over the version number generation

**Comment by larrybradley** [comment]
That was fixed a while ago in https://github.com/astropy/regions/pull/514.  I just need to make a new release.  I'll probably do that very soon so there will also be Python 3.12 wheels.

**Comment by larrybradley** [comment]
Version 0.8 and this is fixed:  
https://astropy-regions.readthedocs.io/en/stable/
