### ISSUE TITLE
Need a new release beyond v0.9

### ISSUE THREAD

**Issue by pllim** [astropy/regions#569]
I noticed that stable `regions` fails integration test but not the dev, so probably means another release is due? See https://github.com/astropy/astropy-integration-testing/actions/runs/11073838092/job/30771294442 for failing log. Thanks.

**Comment by larrybradley** [comment]
Thanks.  This is likely due to https://github.com/astropy/regions/pull/550.

**Comment by larrybradley** [comment]
Version 0.10 is released: https://pypi.org/project/regions/0.10/

**Comment by pllim** [comment]
Thanks!
