### ISSUE TITLE
regions version 0.2

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#63]
This is an overview issue to have a place to discuss about scope, timescale, tasks for the regions version 0.2 release.

Here's the list of issues and pull requests with the 0.2 milestone:
https://github.com/astropy/regions/milestone/4

Of course this is up for debate, any pull request that's ready can go in, and we might put some tasks off to 0.3 if no-one has time to implement them.

**Comment by cdeil** [comment]
@astrofrog made large contributions recently.

I'd like to make a regions 0.2 release soon.
Assigning myself here and putting Dec 5 (a week from now) as tentative release date.

There's no real blocker, but it would be nice to have the MPL plotting sorted out (#76, #77) and also the pytest-arraydiff testing (#80). @astrofrog - Do you have time for those within the next ~ week or should I start a pull request for one of those?

**Comment by astrofrog** [comment]
@cdeil - I have no time, because I have to focus on finishing up the WCSAxes PR to Astropy, so please feel free to go ahead with these changes! I can still review things, just no significant time to **do**.

**Comment by cdeil** [comment]
With #85 merged, I think we are ready for the 0.2 release.
There's no more open issues / PR under the 0.2 milestone, several were moved to 0.3.

The motivation for the release is that we now have:
- New: Mask, BoundingBox, see http://astropy-regions.readthedocs.io/en/latest/getting_started.html#masks
- New: docs section on compound regions: http://astropy-regions.readthedocs.io/en/latest/getting_started.html#compounds
- Improved: docs section on matplotlib plotting: http://astropy-regions.readthedocs.io/en/latest/getting_started.html#matplotlib-plotting and [RectanglePixelRegion](http://astropy-regions.readthedocs.io/en/latest/api/regions.RectanglePixelRegion.html) and [EllipsePixelRegion](http://astropy-regions.readthedocs.io/en/latest/api/regions.EllipsePixelRegion.html) have an `as_patch` method.
- New: Start using Cython in this project, for mask generation
- New: Start using [pytest-arraydiff](https://pypi.python.org/pypi/pytest-arraydiff) in this project, for automated `region.to_mask` testing.
- Several small bug fixes and improvements, see [here](https://github.com/astropy/regions/milestone/4?closed=1) for the list of all pull requests merged between 0.1 and 0.2.

Am I missing something? I would put something like that in the announcement email on astropy-dev.
Maybe it would be simplest if we start a changelog and / or "what's new" sections, and just copy & paste those in the announcement emails?
Then the info would also be available in the package docs.

If there's something you'd like to get in, please file an issue or pull request in the next day or two.

**Comment by cdeil** [comment]
I apologise for not making the release earlier as I said.
How about making the release now or next week?

Is anything except #103 by @larrybradley considered a must-have?
I would like to implement the things we discussed in January, but probably won't be able to take a day or two to do it, and I don't consider this a blocker.
Does anyone have plans to make pull requests in the coming ~ week or are you OK to make a v0.2 release now?

**Comment by cdeil** [comment]
PyPI: https://pypi.python.org/pypi/regions/0.2
Tag: https://github.com/astropy/regions/releases/tag/v0.2

@astropy/regions-developers - Please try installing from the sdist on PyPI and comment here if everything looks good / tests pass for you.

I'll add 0.2 on RTD now.

@bsipocz - Do you have time to kick off the Conda build? Or should I do it?

**Comment by cdeil** [comment]
There's conda install issues on RTD: 
https://readthedocs.org/projects/astropy-regions/builds/5035533/
I'll try to fix that now by updating to newer versions.

**Comment by bsipocz** [comment]
Sure, I can do the conda update.

**Comment by cdeil** [comment]
@bsipocz - Thanks!

I've updated the conda env on RTD in 5addcb9 in `master`.

Anyone know if that can be used to build the v0.2 docs on RTD?
If no -- is there a way I can fix the v0.2 docs build on RTD?

**Comment by bsipocz** [comment]
I guess you can set the label stable for that build, can't you?

**Comment by cdeil** [comment]
I didn't manage to fix the docs build issues on RTD today.
I complained about them here
https://github.com/rtfd/readthedocs.org/issues/2614#issuecomment-280364651
and will try again in the coming days.

**Comment by cdeil** [comment]
The last RTD docs build failed on conda install:
https://readthedocs.org/projects/astropy-regions/builds/5037252/

Next I tried with python 3.5 in 13886b7 and that worked for `latest`:
https://readthedocs.org/projects/astropy-regions/builds/5038871/

But for `v0.2` the docs build fails on RTD, presumably because it's using the docs build setting from that version, not master:
https://readthedocs.org/projects/astropy-regions/builds/5038880/

> I guess you can set the label stable for that build, can't you?

@bsipocz - I don't understand what the `stable` branch has to do with the `v0.2` docs build!?

Anyone familiar with RTD knows how I can get the v0.2 docs build to work?
Is there an option that I do it locally and upload the result to RTD?

**Comment by cdeil** [comment]
Macports package update: https://github.com/macports/macports-ports/pull/327

I'll wait for Mac / Linux conda packages to become available before announcing on astropy-dev:
https://github.com/astropy/conda-channel-astropy/pull/133#issuecomment-280575706

**Comment by cdeil** [comment]
Here's a draft release announcement. Comment welcome.

One question I have: is this the recommended way to upgrade via pip, or should there be an extra flag that prevents updating of dependencies like Numpy or Astropy?

---

Hi all,

I am happy to announce the release of version 0.2 of the regions package.

The regions package features classes to represent pixel and sky regions with methods to do analysis (mainly containment check and mask generation) and matplotlib plotting, as well as DS9 region format serialisation.

Docs: http://astropy-regions.readthedocs.io
Code: https://github.com/astropy/regions

As usual, you can upgrade with pip or conda:

pip install  regions —upgrade
conda upgrade -c astropy regions

This regions package is in an early stage of development. It is not feature complete or API stable. Feedback or contributions highly welcome!
There is a tutorial introduction available that gives an overview of the current features and API here:
http://astropy-regions.readthedocs.io/en/latest/getting_started.html

The 0.2 release contains significant additions such as a PixCoord, BoundingBox and Mask class, as well as efficient circle and polygon pixel containment and mask code written in Cython, added by Tom Robitaille, Larry Bradley and Christoph Deil. Adam Ginsburg implemented several improvements and fixes to the DS9 region serialisation compared to v0.1.

The hope is that regions package development accelerates a bit and that we will reach a status where it’s appropriate to propose it for inclusion in the Astropy core as astropy.regions in time for the Astropy 2.0 release (i.e. by March or April 2017 latest).

Questions, feedback and contributions on this mailing list or on Github are very welcome!

Cheers,
Christoph

**Comment by larrybradley** [comment]
@cdeil  In general, I *think* we recommend using the `--no-deps` flag to prevent pip from unintentionally upgrading dependent packages (e.g. it's recommended in the `photutils` docs).

**Comment by bsipocz** [comment]
@cdeil - What I meant is that you can probably use the "stable" label on RTD and assign it to the build that passed (but was after the official 0.2 release). I haven't tried doing it though, so it's just guesswork. That case you have a stable and a latest RTD, which should be enough I think.

**Comment by bsipocz** [comment]
The conda packages are available now, so I suggest to send out the release announcement and close this issue/milestone.

**Comment by cdeil** [comment]
Mailing list announcement:
https://groups.google.com/forum/#!topic/astropy-dev/uvFZL0zmBcA

I removed the part saying we'll try to finish this package by March or April and propose it to be included in Astropy core in time for 0.2.
This is not really a good idea or feasible at all, unless one or several people start working on it almost full-time for the coming weeks, and we get a lot of user feedback immediately.
So let's see how things go and where we are in 6 weeks.
