### ISSUE TITLE
Document "meta", "visual" and "vizmeta" for regions

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#64]
I saw that all regions (e.g. [CircleSkyRegion](http://astropy-regions.readthedocs.io/en/latest/_modules/regions/shapes/circle.html#CircleSkyRegion)) have `meta` and `visual` arguments in `__init__` and data members:

```
    def __init__(self, center, radius, meta=None, visual=None):
        # TODO: test that center is a 0D SkyCoord
        self.center = center
        self.radius = radius
        self.meta = meta or {}
        self.visual = visual or {}
```

As far as I know these are not documented anywhere (not mentioned as parameters in the docstring), not included in the str representation of the region and not explained here:
http://astropy-regions.readthedocs.io/en/latest/getting_started.html#ds9

I tried this one example ... in this case apparently an extra `vizmeta` attribute is populated with info from the DS9 file:

``` python
>>> from regions import read_ds9
>>> regions = read_ds9('regions/io/tests/data/ds9.color.reg')
>>> regions[0].__dict__
{'center': <FK5 Coordinate (equinox=J2000.000): (ra, dec) in deg
     (202.46947917, 47.19583889)>,
 'meta': {'include': ''},
 'radius': <Quantity 1.0 arcsec>,
 'visual': {},
 'vizmeta': {'color': 'blue'}}
```

Personally my motivation to work on the DS9 aspect of `regions` is small, I want to focus on using regions for analysis, i.e. implement polygons etc.

@keflavich or anyone else familiar with `regions/io` -- could you please write up a page of info and examples that explain how the I/O and these attributes work?
Either extend http://astropy-regions.readthedocs.io/en/latest/getting_started.html#ds9 or better yet, just make a new separate page in the high-level docs.
That could also include a comparison with `pyregion`, how it represents the info from ds9 files and how `regions` is similar or different.

**Comment by keflavich** [comment]
I think this was a placeholder for visualization-based metadata, e.g. what color is the region?  how thick is its border? etc.  Probably `vizmeta` and `visual` are meant to be merged.  I'm not sure we took any written notes on this; @joleroi @astrofrog do you recall?

**Comment by joleroi** [comment]
You're right, The idea was to save 'visual' information such as color, and ... color in a different attribute that other meta information (basically whatever people want to put). I don't recall if we agreed on a name, but if I was to vote now I'd go for ``visual``.

**Comment by astrofrog** [comment]
+1 to ``visual`` over ``vizmeta``

**Comment by joleroi** [comment]
Thanks, ``vizmeta`` sounds like a Pokemon, right?

**Comment by cdeil** [comment]
Looks like there is consensus.

Can someone make a PR renaming `vizmeta` to `visual` and documenting the idea behind `meta` and `visual` in the docs?
https://github.com/astropy/regions/search?utf8=%E2%9C%93&q=vizmeta

**Comment by cdeil** [comment]
I'd like to make a regions 0.2 release soon.
@keflavich, @joleroi, anyone - do you have time to implement this issue within the next ~ week?

**Comment by cdeil** [comment]
Moving to 0.3 milestone.

**Comment by cdeil** [comment]
So by now `vizmeta` isn't mentioned anywhere any more:
```
$ ack vizmeta
```

There's still `meta` and `visual`:
```
$ ack visual
docs/ds9.rst
80:    Also, all regions currently have ``meta`` and ``visual`` arguments for ``__init__``

regions/io/read_ds9.py
229:        reg.visual = {key: meta[key] for key in meta.keys() if key in viz_keywords}

regions/io/tests/test_ds9_language.py
173:    assert regions[0].visual['color'] == 'green'
174:    assert regions[1].visual['color'] == 'orange'
190:    assert regions[0].visual['color'] == 'green'
191:    assert regions[1].visual['color'] == 'orange'
192:    assert regions[2].visual['color'] == 'blue'

regions/shapes/annulus.py
31:    def __init__(self, center, inner_radius, outer_radius, meta=None, visual=None):
71:    def __init__(self, center, inner_radius, outer_radius, meta=None, visual=None):

regions/shapes/circle.py
28:    def __init__(self, center, radius, meta=None, visual=None):
32:        self.visual = visual or {}
114:    def __init__(self, center, radius, meta=None, visual=None):
119:        self.visual = visual or {}

regions/shapes/ellipse.py
63:                 visual=None):
70:        self.visual = visual or {}
102:                                meta=self.meta, visual=self.visual)
208:    def __init__(self, center, width, height, angle=0. * u.deg, meta=None, visual=None):
215:        self.visual = visual or {}
227:                                  meta=self.meta, visual=self.visual)

regions/shapes/line.py
27:    def __init__(self, start, end, meta=None, visual=None):
31:        self.visual = visual or {}
94:    def __init__(self, start, end, meta=None, visual=None):
99:        self.visual = visual or {}

regions/shapes/point.py
22:    def __init__(self, center, meta=None, visual=None):
26:        self.visual = visual or {}
71:    def __init__(self, center, meta=None, visual=None):
75:        self.visual = visual or {}

regions/shapes/polygon.py
25:    def __init__(self, vertices, meta=None, visual=None):
28:        self.visual = visual or {}
116:    def __init__(self, vertices, meta=None, visual=None):
120:        self.visual = visual or {}

regions/shapes/rectangle.py
61:    def __init__(self, center, width, height, angle=0 * u.deg, meta=None, visual=None):
68:        self.visual = visual or {}
112:                                  meta=self.meta, visual=self.visual)
221:    def __init__(self, center, width, height, angle=0 * u.deg, meta=None, visual=None):
228:        self.visual = visual or {}
240:                                    meta=self.meta, visual=self.visual)
```

@keflavich @joleroi - Is this solution now OK, with `meta` and `visual` how it is?
Before closing this issue, could you please update this docs page, removing the warning at the end, and giving an example where both `meta` and `visual` are used?
```
docs/ds9.rst
80:    Also, all regions currently have ``meta`` and ``visual`` arguments for ``__init__``
```

**Comment by cdeil** [comment]
@keflavich or @sushobhana - Can this old issue from 2016 / 2017 be closed? Or is there an action item left?
