### ISSUE TITLE
ds9 region parsing should handle whitespace

### ISSUE THREAD

**Issue by keflavich** [astropy/regions#65]
As per https://github.com/astropy/pyregion/issues/73, there are some regions that are valid for ds9 but are not included in the test cases now and are not properly parsed.

**Comment by sushobhana** [comment]
hi @keflavich ,
i went to said issue and tried to reproduce the error. the problem i saw  that it doesn't identify `J2000` as a coordinate system. i think it should be mapped to `fk5` and it seems to handles whitespace pretty well ( i only tried to reproduce the example given: `'J2000; circle 188.5557102 12.0314056 1" # color=red' `). it seems to work after that..

**Comment by keflavich** [comment]
If you think you've found a solution, yes, go ahead and open a PR.  I'm not entirely sure the J2000 frame is the problem, given the description in the other issue, but it might be.

**Comment by sushobhana** [comment]
@keflavich initially i thought the same. But i built it and it's working.! Do have a look over the PR.

**Comment by larrybradley** [comment]
This issue is fixed.
