### ISSUE TITLE
Remove 'all' and 'any' models from to_mask API?

### ISSUE THREAD

**Issue by astrofrog** [astropy/regions#72]
The 'all' and 'any' modes are maybe not needed - one can just use 'exact' and check the result compared to 0 and 1. In fact, this is hard to implement internally because for 'all', the exact mode can sometimes give results are are extremely close but not exactly 1 - so then we have to introduce a tolerance, which gets messy. I'd actually vote to remove these modes and just keep 'center', 'subpixels', and 'exact'. What do others think?

**Comment by larrybradley** [comment]
Sounds good to me!

**Comment by cdeil** [comment]
+1

**Comment by astrofrog** [comment]
I've done that in https://github.com/astropy/regions/pull/71, but will leave this open in case anyone else has objections

**Comment by bsipocz** [comment]
👍

**Comment by astrofrog** [comment]
Done in #71
