### ISSUE TITLE
Attribute validation for astropy.regions?

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#83]
In https://github.com/astropy/regions/pull/81#issuecomment-263240526 and other places in `astropy.regions` before the question came up whether we should do input validation (for `PixCoord`, `BoundingBox`, region classes with float or Angle or SkyCoord attributes, ....

I'm +1 to do it. It's some extra effort for us, but especially for interactive work it really helps users catch many little mistakes.

My preference would be to use something like [attrs](https://glyph.twistedmatrix.com/2016/08/attrs.html) or [numtraits](https://pypi.python.org/pypi/numtraits) instead of re-implementing something similar again here in `astropy.regions`.

@astrofrog @larrybradley or anyone - Thoughts?

Is there something available or proposed in Astropy core?
Should we bundle or add dependency here?
Should we discuss on the Astropy mailing list or issue tracker now, or just go ahead and start using something here and discuss later / hope they accept it in Astropy core?

**Comment by cdeil** [comment]
I don't know if there's some data validation descriptors in Astropy already and given that this package is small and our needs are modest I wouldn't suggest something like attrs or traits, so having a few custom descriptor classes here in the regions package seems fine.

I had a very quick look at your descriptor implementations.

It looks like you have a mix of using `WeakKeyDictionary` and some where you use the instance to store the value and use getattr from the descriptor. Is there a logic to that or can this be simplified / unified a little?

Personally I find it weird to have a `WeakKeyDictionary` and have the values not stored on the instances, and like the pattern to keep the values in the instance dict as usual, and only use the descriptor for validation and modify the instance dict from the descriptor. This is explained [here](http://nbviewer.jupyter.org/urls/gist.github.com/ChrisBeaumont/5758381/raw/descriptor_writeup.ipynb#Beware-unhashable-descriptor-owners). Really the only drawback is that you have to put the same attribute and descriptor label name, which I don't find hard to get right because it's on a single line.

**Comment by sushobhana** [comment]
Actually the logic is : the key of the `WeakKeyDictionary` is an instance of the `regions.Region` class and it's value is the value of the attribute . We use weak dictionary so that the key value pair exists until the instance is alive, hence prevents memory leakage.
We store it in this way because the descriptor classes are static to it's owner class. 
The problem with this arises only when the instances are unhashable, which is not the case for `regions.Region` (according to the link, you provided).
Thanks for the link btw!!

**Comment by cdeil** [comment]
Yes, what I dislike about this is that the data isn't stored in the region instances, but in a global dict in the descriptor. I didn't review your code carefully, but probably it's all good, this is one valid pattern to use descriptors. It just isn't my preference. If you prefer to keep as-is, we can just close this issue. (I don't have time to hack on regions anyways unfortunately.)

**Comment by sushobhana** [comment]
hmm, I get it . It kind of looks lil ugly. I will try to find some other way, if I get some time. Let's keep it open then. Thanks!

**Comment by cdeil** [comment]
I changed the descriptor implementation in #284 .

I'm still not very happy with https://github.com/astropy/regions/blob/master/regions/core/attributes.py

- Suggest to split out Meta, RegionMeta and RegionVisual into a separate file `regions/core/meta.py`
- Suggest to improve the names of the descriptors. E.g. `CompoundRegionSky` sounds like a region, but it's not, it's a descriptor for a SkyCoord`.
- We could consider choosing a standard solution like https://www.attrs.org/ or https://docs.python.org/3/library/dataclasses.html which is simpler and more powerful instead of maintaining our own set of validators. Probably this only makes sense if Astropy core adopts them, otherwise we should stick with our homegrown or if it exists use something from Astropy core.
