### ISSUE TITLE
Improve ellipse regions

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#86]
I'd like to propose a few changes to the ellipse regions, [EllipsePixelRegion](http://astropy-regions.readthedocs.io/en/latest/api/regions.EllipsePixelRegion.html) and [EllipseSkyRegion](http://astropy-regions.readthedocs.io/en/latest/api/regions.EllipseSkyRegion.html), that I don't have time for now to implement in #85.

- [ ] Rename parameter `major` -> `a` and `minor` -> `b`. These are the names that were previously chosen for [astropy.modeling.functional_models.Ellipse2D](http://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Ellipse2D.html) and [photutils.aperture.EllipticalAperture](http://photutils.readthedocs.io/en/latest/api/photutils.aperture.EllipticalAperture.html).
- [ ] The ellipse mask test in `regions/shapes/tests/test_masks.py` currently uses `EllipsePixelRegion(PixCoord(3.981987, 4.131378), major=2.2233, minor=3.3411, angle=32 * u.deg)`, i.e. minor > major, probably due to a misunderstanding in the argument order. I suggest we change this test to use `a > b` and update the reference results files, even if `a` and `b` are no longer called major and minor.
- [ ] The description of `a` and `b` should not claim they are the major and minor axis. That's a can of worms, because sometimes `a > b` and `b < a`, we don't have any control over that in the code. This should also be fixed in the [astropy.modeling.functional_models.Ellipse2D](http://docs.astropy.org/en/latest/api/astropy.modeling.functional_models.Ellipse2D.html) docstring, I think there's already an issue with no action discussing that. We can expose extra attributes `major` and `minor` if people want, or a method that returns a new shape where always `a>b` if people think that's useful.

Just overall, I think it's important that we finish the photutils aperture -> astropy regions code transition soon and systematically and someone spend a week to do that. We're wasting time looking at the same issues that have already been discussed, sorted out and are coded up and tested in `photutils`. (I'm not saying we have to do everything the same, this is a chance to fix inconsistencies and mistakes we made in photutils if any.)

Putting this on the 0.3 milestone. Help wanted!

**Comment by astrofrog** [comment]
Could we use ``width`` and ``height`` instead of ``a`` and ``b`` to be consistent with Rectangle and also the terminology ds9 uses?

**Comment by cdeil** [comment]
@astrofrog - Assigning to you for a decision.

Maybe @joleroi , @keflavich @larrybradley can comment here or you can briefly discuss in at #pyastro17?

For me "a" and "b" would be OK (see reasoning above), and "width" and "height" would be fine as well.

**Comment by keflavich** [comment]
I'm OK with `width` and `height`, though I actually prefer `minor`/`major` with enforcement since height is not typically used to describe ellipses.

I am strongly opposed to one-letter variable names such as `a`, `b`.

**Comment by astrofrog** [comment]
After discussing this with @keflavich we decided ``width/height`` would make sense as the core representation but it would be nice to have a way to derive a major/minor/position angle representation

**Comment by astrofrog** [comment]
@cdeil - in #132 I changed to use width/height for ellipses, which removes the ambiguity about whether an axis is 'major' or 'minor' and whether we should enforce 'major' > 'minor'. So I think we can close this?

**Comment by cdeil** [comment]
OK, thanks!
