### ISSUE TITLE
Split up getting started into multiple pages?

### ISSUE THREAD

**Issue by cdeil** [astropy/regions#89]
As discussed with @astrofrog in https://github.com/astropy/regions/pull/87#issuecomment-264001695, the http://astropy-regions.readthedocs.io/en/latest/getting_started.html page is getting too long and we should probably split it up.

It's not quite clear how to best do it. At the moment there's ~ 16 sections.
Some are very short, is putting each on a sub-page a good solution?
Or maybe just move some of the longer ones (like masks and plotting) on sub-sections?

One point to keep in mind is that we want this to become `astropy.regions`, so the docs should be as similar as possible to the existing structure of Astropy core sub-package docs:
http://astropy.readthedocs.io/en/latest/

I'm pretty sure we do need docs sub-pages, because we'll also add things like MOC (healpix-based regions) here (see #62), so `astropy.regions` will grow in the coming months.

I'm putting this under the 0.2 milestone, and can spend some time on it, but not much.
So comments on what we should do or even help welcome!

**Comment by astrofrog** [comment]
I'm working on this at #pyastro17

**Comment by astrofrog** [comment]
Done in #132
